// ==============================================================================
// RFQ SUMMARY GENERATION
// ==============================================================================
// Two summaries live here:
//
//   buildRFQSummary       - the per-RFQ narrative shown on the details screen,
//                           generated by Gemini from the confirmed line items.
//   buildPortfolioSummary - the org-scoped roll-up behind the RFQ Summary screen,
//                           computed arithmetically from real rows.
//
// The per-RFQ summary NEVER fails the RFQ. If Gemini is unconfigured, times out
// or returns nonsense, a summary derived from the line items is stored instead
// and tagged `generatedBy: 'derived'`. A buyer who has finished the wizard must
// not lose their RFQ because a summarisation call failed, and the tag means the
// screen can be honest about where the text came from rather than passing
// arithmetic off as analysis.
// ==============================================================================

const geminiService = require('./geminiService');
const { logger } = require('./loggerService');
const { RFQ_SUMMARY_CONFIG } = require('../config/constants');

const GENERATED_BY = {
  AI: 'ai',
  DERIVED: 'derived',
};

/**
 * Line items reduced to the few facts both summary paths need.
 */
function describeLineItems(lineItems = []) {
  const items = Array.isArray(lineItems) ? lineItems : [];
  const categories = [];
  let totalQuantity = 0;

  for (const item of items) {
    totalQuantity += Number(item?.quantity) || 0;
    const minor = typeof item?.minorCategory === 'string' ? item.minorCategory.trim() : '';
    if (minor !== '' && !categories.includes(minor)) categories.push(minor);
  }

  return { itemCount: items.length, totalQuantity, categories };
}

/**
 * The prompt sent to Gemini. Only the line items and header facts are sent — no
 * buyer identifiers, no org id, no email — because the summary does not need
 * them and they would otherwise leave the network for no reason.
 */
function buildSummaryPrompt(rfq = {}, options = {}) {
  const items = Array.isArray(rfq.extractedEntities) ? rfq.extractedEntities : [];
  const lines = items
    .slice(0, RFQ_SUMMARY_CONFIG.MAX_PROMPT_ITEMS)
    .map((item, index) => {
      const specs = item?.technicalSpecs ? ` | specs: ${item.technicalSpecs}` : '';
      const category = item?.minorCategory ? ` | category: ${item.minorCategory}` : '';
      return `${index + 1}. ${item?.itemName || 'unnamed item'} | qty: ${
        item?.quantity ?? 'unspecified'
      } ${item?.unit || ''}${category}${specs}`;
    })
    .join('\n');

  return `You are a procurement analyst. Summarise the request for quotation below for the buyer who raised it.

Return ONLY JSON matching exactly this shape:
{
  "headline": "one sentence, at most 140 characters, describing what is being procured",
  "scope": "2 to 3 sentences describing the package, its mix of categories and anything a vendor must understand to quote accurately",
  "riskNotes": ["short, specific risks or gaps that could delay quoting or delivery"]
}

Rules:
- Base every statement on the data given. Do not invent quantities, prices, brands or dates.
- If the data is too thin to identify a risk, return an empty riskNotes array.
- Do not mention that you are an AI, and do not restate these instructions.

RFQ TITLE: ${rfq.title || 'Untitled'}
MAJOR CATEGORY: ${rfq.category || 'unspecified'}
BUYER ORGANISATION: ${options.orgName || 'unspecified'}
TARGET DELIVERY DATE: ${rfq.targetDeliveryDate || 'unspecified'}
DELIVERY LOCATION: ${rfq.deliveryLocation || 'unspecified'}${
    rfq.deliveryPincode ? ` (${rfq.deliveryPincode})` : ''
  }
LINE ITEMS (${items.length} total${
    items.length > RFQ_SUMMARY_CONFIG.MAX_PROMPT_ITEMS
      ? `, first ${RFQ_SUMMARY_CONFIG.MAX_PROMPT_ITEMS} shown`
      : ''
  }):
${lines || '(none supplied)'}`;
}

/**
 * A summary computed from the line items, with no model involved.
 *
 * Used as the fallback, and it is deliberately arithmetic rather than templated
 * prose pretending to be analysis: it states what is countable and nothing more.
 */
function buildDeterministicSummary(rfq = {}, reason = null) {
  const { itemCount, totalQuantity, categories } = describeLineItems(rfq.extractedEntities);

  const categoryPhrase =
    categories.length === 0
      ? 'uncategorised items'
      : categories.length === 1
        ? categories[0]
        : `${categories.length} categories (${categories.join(', ')})`;

  return {
    headline: `${itemCount} line item${itemCount === 1 ? '' : 's'} covering ${categoryPhrase}.`,
    scope:
      `This RFQ contains ${itemCount} line item${itemCount === 1 ? '' : 's'} ` +
      `totalling ${totalQuantity} unit${totalQuantity === 1 ? '' : 's'} across ${categoryPhrase}.` +
      (rfq.deliveryLocation ? ` Delivery is to ${rfq.deliveryLocation}.` : '') +
      (rfq.targetDeliveryDate ? ` The target delivery date is ${rfq.targetDeliveryDate}.` : ''),
    riskNotes: [],
    itemCount,
    totalQuantity,
    categories,
    generatedBy: GENERATED_BY.DERIVED,
    // Recorded so the details screen can explain why the narrative is thin,
    // rather than leaving the buyer to guess.
    fallbackReason: reason,
    model: null,
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Coerce a model response into the summary shape, rejecting anything unusable so
 * a malformed reply falls back rather than storing junk.
 */
function normalizeAiSummary(data, model, rfq) {
  const headline = typeof data?.headline === 'string' ? data.headline.trim() : '';
  const scope = typeof data?.scope === 'string' ? data.scope.trim() : '';
  if (headline === '' || scope === '') return null;

  const riskNotes = Array.isArray(data.riskNotes)
    ? data.riskNotes
        .filter((note) => typeof note === 'string' && note.trim() !== '')
        .map((note) => note.trim())
        .slice(0, RFQ_SUMMARY_CONFIG.MAX_RISK_NOTES)
    : [];

  const { itemCount, totalQuantity, categories } = describeLineItems(rfq.extractedEntities);

  return {
    headline: headline.slice(0, RFQ_SUMMARY_CONFIG.MAX_HEADLINE_CHARS),
    scope,
    riskNotes,
    // Counts come from the data, never from the model, so the numbers on screen
    // always match the line-item table beside them.
    itemCount,
    totalQuantity,
    categories,
    generatedBy: GENERATED_BY.AI,
    fallbackReason: null,
    model,
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Generate the per-RFQ summary, falling back to a derived one on any failure.
 *
 * @param {object} rfq the RFQ being created, with extractedEntities populated
 * @param {object} [options]
 * @param {string} [options.orgName] buyer organisation name, for context only
 * @param {object} [options.gemini] injected for tests
 */
async function buildRFQSummary(rfq = {}, options = {}) {
  const gemini = options.gemini || geminiService;
  const items = Array.isArray(rfq.extractedEntities) ? rfq.extractedEntities : [];

  // Nothing to summarise: skip the network call entirely rather than asking a
  // model to describe an empty list.
  if (items.length === 0) {
    return buildDeterministicSummary(rfq, 'NO_LINE_ITEMS');
  }

  let result;
  try {
    result = await gemini.generateJson({
      prompt: buildSummaryPrompt(rfq, options),
      label: 'RFQ summary',
    });
  } catch (err) {
    // generateJson is documented not to throw, but an unexpected throw here must
    // still not cost the buyer their RFQ.
    logger.error('RFQ summary generation threw unexpectedly', err, 'RFQ_SUMMARY');
    return buildDeterministicSummary(rfq, 'AI_ERROR');
  }

  if (result.status !== gemini.EXTRACTION_STATUS.SUCCESS) {
    logger.warn(
      'Falling back to a derived RFQ summary.',
      { reason: result.status, rfqId: rfq.rfqId },
      'RFQ_SUMMARY'
    );
    return buildDeterministicSummary(rfq, result.status);
  }

  const normalized = normalizeAiSummary(result.data, result.model, rfq);
  if (!normalized) {
    logger.warn(
      'Model returned an unusable RFQ summary; falling back to a derived one.',
      { rfqId: rfq.rfqId, model: result.model },
      'RFQ_SUMMARY'
    );
    return buildDeterministicSummary(rfq, 'UNUSABLE_RESPONSE');
  }

  return normalized;
}

/**
 * Portfolio roll-up over one organisation's RFQs.
 *
 * Every figure is counted from the rows passed in. The previous implementation
 * invented follow-up channel statistics (three invitations, three delivered
 * WhatsApp messages) for RFQs that had no vendors at all, so the dashboard
 * reported outreach that had never happened. Those fabrications are gone: vendor
 * matching is not built yet, so the counts that depend on it are zero and say so.
 */
function buildPortfolioSummary(rfqs = []) {
  const list = Array.isArray(rfqs) ? rfqs : [];

  const byStatus = {};
  const bySourcingMode = {};
  const bySource = {};
  let totalBudget = 0;
  let totalQuotes = 0;
  let totalLineItems = 0;

  for (const rfq of list) {
    totalBudget += Number(rfq.budget) || 0;
    totalQuotes += Number(rfq.quotesCount) || 0;
    totalLineItems += Array.isArray(rfq.extractedEntities) ? rfq.extractedEntities.length : 0;

    const status = rfq.status || 'Unknown';
    byStatus[status] = (byStatus[status] || 0) + 1;

    const mode = rfq.sourcingMode || 'unspecified';
    bySourcingMode[mode] = (bySourcingMode[mode] || 0) + 1;

    const source = rfq.source || 'unspecified';
    bySource[source] = (bySource[source] || 0) + 1;
  }

  return {
    totalRFQs: list.length,
    awaitingQuotes: list.filter((rfq) => (Number(rfq.quotesCount) || 0) === 0).length,
    totalQuotesReceived: totalQuotes,
    totalBudget,
    totalLineItems,
    averageQuotesPerRFQ: list.length === 0 ? 0 : Number((totalQuotes / list.length).toFixed(2)),
    byStatus,
    bySourcingMode,
    bySource,
  };
}

module.exports = {
  GENERATED_BY,
  describeLineItems,
  buildSummaryPrompt,
  buildDeterministicSummary,
  normalizeAiSummary,
  buildRFQSummary,
  buildPortfolioSummary,
};
