// ==============================================================================
// SEED DATA
// ==============================================================================
// Reference dataset the in-memory enterprise store boots from. This module is
// pure data with no database coupling: user accounts are persisted in the shared
// MySQL identity schema (see db/identityQueries.js), and the domain records
// below are served from storeService.
// ==============================================================================

const SEED_VENDORS = [
  {
    id: 'v-001',
    name: 'Apex Industrial Dynamics Pvt Ltd',
    contactPerson: 'Rajesh Nair',
    email: 'rajesh@apexindustrial.in',
    phone: '+91 98201 44820',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Pumps & Accessories', 'Compressors & Accessories', 'Machinery Parts'],
    location: 'Bhosari Industrial Estate, Pune, Maharashtra',
    rating: 4.8,
    score: 92.4,
    source: 'buyer_uploaded',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    evaluated: true,
    hasRecord: true,
    matchReason: 'Empanelled Tier-1 Vendor with 100% Quality Conformance',
    proximity: 'Local (within 50km)',
    proximityMatch: true,
    isExistingInDatabase: true,
    onboardingEmailStatus: 'sent',
    tempPassword: 'Procucev#2026!Apex',
    firstLoginCompleted: true,
    reminderCadence: 'every_3_days',
    addedByBuyerCompany: 'Tata Motors Commercial Vehicles Ltd.',
    clientMappedCategories: ['Pumps & Accessories', 'Compressors & Accessories'],
    vendorSelectedCategories: ['Pumps & Accessories', 'Compressors & Accessories', 'Machinery Parts'],
    isCategoryAligned: true,
  },
  {
    id: 'v-002',
    name: 'Precision Hydro-Pneumatics Ltd',
    contactPerson: 'Sanjay Verma',
    email: 'sanjay@precisionhydro.com',
    phone: '+91 98112 33455',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Hoses, Valves & Fittings', 'Pipes & Pipe Fittings'],
    location: 'Peenya Industrial Area, Bengaluru, Karnataka',
    rating: 4.6,
    score: 88.5,
    source: 'buyer_uploaded',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    evaluated: true,
    hasRecord: true,
    matchReason: 'ISO 9001:2015 & IATF 16949 Certified Hydraulics Fabricator',
    proximity: 'Regional (South Hub)',
    proximityMatch: false,
    isExistingInDatabase: true,
    onboardingEmailStatus: 'sent',
    tempPassword: 'Procucev#2026!Hydro',
    firstLoginCompleted: true,
    reminderCadence: 'every_3_days',
    addedByBuyerCompany: 'Larsen & Toubro Heavy Engineering Division',
    clientMappedCategories: ['Hoses, Valves & Fittings'],
    vendorSelectedCategories: ['Hoses, Valves & Fittings', 'Pipes & Pipe Fittings'],
    isCategoryAligned: true,
  },
  {
    id: 'v-003',
    name: 'Bharat Electricals & Switchgear Corp',
    contactPerson: 'Anil Mehta',
    email: 'anil.mehta@bharatelec.in',
    phone: '+91 98450 67890',
    majorCategory: 'Engineering Spares - Electrical',
    minorCategories: ['Panels', 'Circuit Breakers', 'Transformers'],
    location: 'Sanand Industrial Hub, Ahmedabad, Gujarat',
    rating: 4.9,
    score: 95.0,
    source: 'procucev_network',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    evaluated: true,
    hasRecord: true,
    matchReason: 'Double-Blind AI Network Match with CPRI Type-Tested Switchgear',
    proximity: 'Regional (West Hub)',
    proximityMatch: false,
    isExistingInDatabase: true,
    onboardingEmailStatus: 'sent',
    tempPassword: 'Procucev#2026!Bharat',
    firstLoginCompleted: true,
    reminderCadence: 'every_3_days',
    addedByBuyerCompany: 'Tata Motors Commercial Vehicles Ltd.',
    clientMappedCategories: ['Panels', 'Circuit Breakers'],
    vendorSelectedCategories: ['Panels', 'Circuit Breakers', 'Transformers'],
    isCategoryAligned: true,
  },
  {
    id: 'v-004',
    name: 'Kirloskar Flow Technologies Ltd',
    contactPerson: 'Vikram Joshi',
    email: 'vikram.joshi@kirloskarflow.com',
    phone: '+91 98220 11223',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Pumps & Accessories', 'Motors', 'Customised Parts'],
    location: 'Kirloskarvadi, Sangli, Maharashtra',
    rating: 4.7,
    score: 91.2,
    source: 'buyer_uploaded',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    evaluated: true,
    hasRecord: true,
    matchReason: 'Empanelled Heavy Duty Slurry & Boiler Feed Pump Specialist',
    proximity: 'Regional (Maharashtra)',
    proximityMatch: true,
    isExistingInDatabase: true,
    onboardingEmailStatus: 'sent',
    tempPassword: 'Procucev#2026!Kirloskar',
    firstLoginCompleted: true,
    reminderCadence: 'every_3_days',
    addedByBuyerCompany: 'JSW Steel Energy & Industrial Infrastructure',
    clientMappedCategories: ['Pumps & Accessories', 'Motors'],
    vendorSelectedCategories: ['Pumps & Accessories', 'Motors', 'Customised Parts'],
    isCategoryAligned: true,
  },
  {
    id: 'v-005',
    name: 'Godrej Precision Tooling & Dies',
    contactPerson: 'Meera Rao',
    email: 'meera.rao@godrejtooling.com',
    phone: '+91 98670 99881',
    majorCategory: 'Customized Machining Parts',
    minorCategories: ['CNC Machined Castings', 'Forged Gears & Shafts', 'Precision Fixtures'],
    location: 'Vikhroli, Mumbai, Maharashtra',
    rating: 4.8,
    score: 93.8,
    source: 'procucev_network',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    evaluated: true,
    hasRecord: true,
    matchReason: 'Aerospace & Heavy Commercial Grade 5-Axis CNC Facility',
    proximity: 'Local (Mumbai Hub)',
    proximityMatch: true,
    isExistingInDatabase: true,
    onboardingEmailStatus: 'sent',
    tempPassword: 'Procucev#2026!Godrej',
    firstLoginCompleted: true,
    reminderCadence: 'every_3_days',
    addedByBuyerCompany: 'Mahindra & Mahindra Farm Equipment Division',
    clientMappedCategories: ['CNC Machined Castings', 'Precision Fixtures'],
    vendorSelectedCategories: ['CNC Machined Castings', 'Forged Gears & Shafts', 'Precision Fixtures'],
    isCategoryAligned: true,
  },
];

const SEED_EVALUATIONS = [
  {
    id: 'eval-001',
    vendorId: 'v-001',
    vendorName: 'Apex Industrial Dynamics Pvt Ltd',
    contactPerson: 'Rajesh Nair',
    email: 'rajesh@apexindustrial.in',
    phone: '+91 98201 44820',
    category: 'Engineering Spares - Mechanical',
    submissionDate: '2026-08-20',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    overallScore: 92.4,
    systemAction: 'Full Qualification Approved - Circulate High-Value RFQs with Automated PO Issuance',
    moduleScores: {
      commercial: { score: 95, maxScore: 100, weight: 25, weightedScore: 23.75 },
      technical: { score: 90, maxScore: 100, weight: 15, weightedScore: 13.5 },
      quality: { score: 94, maxScore: 100, weight: 20, weightedScore: 18.8 },
      delivery: { score: 92, maxScore: 100, weight: 20, weightedScore: 18.4 },
      financial: { score: 88, maxScore: 100, weight: 10, weightedScore: 8.8 },
      governance: { score: 92, maxScore: 100, weight: 10, weightedScore: 9.2 },
    },
    documents: [
      { id: 'doc-1', name: 'GST_Registration_Certificate.pdf', type: 'Statutory Tax', uploadDate: '2026-08-20', verified: true, status: 'Verified' },
      { id: 'doc-2', name: 'ISO_9001_2015_Certificate.pdf', type: 'Quality Assurance', uploadDate: '2026-08-20', verified: true, status: 'Verified' },
      { id: 'doc-3', name: 'Audited_Financials_FY25.pdf', type: 'Financial Statements', uploadDate: '2026-08-20', verified: true, status: 'Verified' },
    ],
  },
];

module.exports = {
  SEED_VENDORS,
  SEED_EVALUATIONS,
};
