// ==============================================================================
// CATEGORY TAXONOMY TEST FIXTURE
// ==============================================================================
// A stand-in for the `category_division` master, in the grouped shape
// `GET /api/buyer-profile/categories` returns.
//
// This replaces the `@/lib/categories.json` these suites used to import. That file
// was a copy of the master bundled into the client bundle, and deleting it is the
// point: the taxonomy is fetched from the database at runtime now, so a test has
// to supply it the same way the app receives it — through the store, or through a
// mocked `useApp()`.
//
// Kept outside `__tests__/` deliberately: jest.config's testMatch treats every
// file under that directory as a suite, so a fixture placed there would be
// collected and fail as a file containing no tests.
//
// Division order and every spelling below are taken from the real master, because
// several screens assert against specific entries ('Cables', 'Fasteners',
// 'Hoses, Valves & Fittings'). Civil Works is first by `created_ts`, not
// alphabetically, which is the order buyers see and the order assertions that
// index into positions 0 and 1 depend on.
//
// Adding a category a screen needs is expected; renaming one is not — the names
// have to match the master or a genuine assertion silently becomes a fixture gap.
// ==============================================================================

import type { MajorMinorCategory } from '@/lib/types';

export const CATEGORY_TAXONOMY_FIXTURE: MajorMinorCategory[] = [
  {
    majorCategory: 'Civil Works',
    minorCategories: [
      'Back filing',
      'Bricks',
      'Drilling',
      'Excavation',
      'Flooring Material',
      'Gypsum Board',
      'Interior Finishes',
      'Ladders & Scaffolding',
      'PEB Structure',
      'PUF Wall Partition',
      'Painting',
      'Paints',
      'Piling',
      'Plumbing',
      'Rain Water Gutters',
      'Roofing',
      'Roofing Sheets',
      'Sign boards',
      'TMT BARS',
      'Vinyl Sheet',
      'Waterproofing',
    ],
  },
  {
    majorCategory: 'Professional Services',
    minorCategories: [
      'Consultant',
      'Design consultancy',
      'Erection and Commissioning',
      'Events & Exhibitions',
      'Fumigation Service',
      'House Keeping Service',
      'Installation Service',
      'Manpower Service',
      'Marketing Services',
      'Painting Service',
      'Pest Control Service',
      'Security Service',
      'Tax Consultant',
    ],
  },
  {
    majorCategory: 'Engineering Spares - Electrical',
    minorCategories: [
      'Batteries',
      'Brushes',
      'Cables',
      'Ceramic Insulators',
      'Circuit Breakers',
      'Connectors',
      'Control & Instrument',
      'Controllers',
      'Converters',
      'DG Parts',
      'Earthing Items',
      'Electrical Capacitors',
      'Electrical Insulators',
      'Electrical-Lv Switch Gears',
      'Electronic Items',
      'Lights',
      'Load Cells',
      'Motors',
      'Other Electrical Items',
      'Panels',
      'Scanners',
      'Semiconductors',
      'Sensors',
      'Switchs',
      'Transformers',
      'Transmissions',
      'Transmitters',
      'Wires',
    ],
  },
  {
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: [
      'Abrasives',
      'Adhesives & Sealants',
      'Aerospace Components',
      'Air curtains',
      'Automotive Spares',
      'Bearings & Accessories',
      'Belts, Couplings, Pulley & Chains',
      'Blades',
      'Blowers',
      'Boilers',
      'Brakes',
      'Burners',
      'Cast Iron Parts',
      'Ceramic Items',
      'Clamps',
      'Coils',
      'Compressors & Accessories',
      'Consumables',
      'Conveyors',
      'Customised Parts',
      'Cylinders',
      'Die Casting',
      'Drives',
      'Dust Collectors',
      'Dyes & Pigments',
      'Engine Parts',
      'Excavator Attachments',
      'Explosives',
      'Fabrication',
      'Fasteners',
      'Filters',
      'Foundry Moulds',
      'Furnace',
      'Gauges & Instruments',
      'Gearboxes & Spares',
      'Grinding Materials',
      'Hardwares',
      'Heat Exchangers',
      'Hoses, Valves & Fittings',
      'Industrial Fans',
      'Injection Molding',
      'Lifting Chains',
      'Lifting Equipments',
      'Machinery Parts',
      'Material Handling Equipment Spares',
      'Mining Equipment & Spares',
      'Nozzles',
      'O-Rings / Gasket / Seals',
      'Pipes & Pipe Fittings',
      'Pumps & Accessories',
      'Refractories',
      'Regulators',
      'Repair Kits',
      'Rollers',
      'Rubber Goods',
      'Screens',
      'Shafts',
      'Solder Paste',
      'Solenoids',
      'Springs',
      'Storage Tanks',
      'Tools & Tackles',
      'Vacuum Equipment',
      'Vessels',
      'Welding Equipment & Cutting Machines',
      'Welding Materials',
      'Wheels',
    ],
  },
  {
    majorCategory: 'Raw Material',
    minorCategories: [
      'Aluminium',
      'Ash',
      'Brass Components',
      'Chemicals',
      'Coal',
      'Copper',
      'Cotton',
      'Edible Oil',
      'Ferrous Material & Metals',
      'Gases',
      'Lubricants',
      'Minerals',
      'Paper',
      'Pigments',
      'Polyster Materials',
      'Refractories',
      'Rubber',
      'Steels',
      'Wood',
      'Yarn',
    ],
  },
  {
    majorCategory: 'IT',
    minorCategories: [
      'Audio Visual Equipment',
      'BARCODE SCANNERS',
      'CCTV',
      'Computer',
      'Hardware',
      'IT Consumables',
      'Laptop',
      'Networking Equipment',
      'Printers',
      'Servers',
      'Software',
      'Telecom & Security Products',
    ],
  },
  {
    majorCategory: 'Logistics',
    minorCategories: [
      'Air Logistics',
      'Courier & Parcel',
      'Road transport',
      'Sea Logistics',
    ],
  },
  {
    majorCategory: 'Packing Material',
    minorCategories: [
      'Adhevise Printing',
      'Bubble Rolls',
      'Corrugated Boxes',
      'Corrugated Rolls',
      'Drums',
      'Gifting',
      'Hdpe Bottles',
      'Labels & Tags',
      'Laminated pouch',
      'Leather Products',
      'Pallets',
      'Paper Boxes',
      'Paper Printing',
      'Paper rolls',
      'Pet Jars',
      'Pine wood',
      'Plastic Packaging',
      'Shrink Flims',
      'Strapping Machines',
      'Tapes',
      'Thermocol Materials',
      'woven Bags',
    ],
  },
  {
    majorCategory: 'Occuptional Health and Safety',
    minorCategories: [
      'Fire Extinguishers',
      'Gloves',
      'Harness',
      'Hemlets',
      'Medicines',
      'Public Announcement System (PAS)',
      'Safety Shoes',
      'Safety jackets',
      'Seafty Equipments',
    ],
  },
  {
    majorCategory: 'CAPEX - Equipment & Machinery',
    minorCategories: [
      'Agriculture Equipments',
      'Air Conditioners',
      'Ambulances',
      'Briquetting machines',
      'CNC Machines',
      'Cement Bulkers',
      'Construction Equipment',
      'Containers',
      'Conveyors',
      'Cranes',
      'Diesel Gensets',
      'Dumpers',
      'Earth Moving Equipment',
      'Electric Vehicles',
      'Elevators',
      'Excavators',
      'Food processing Machine',
      'Fork Lifts',
      'Gardening Equipment',
      'Hydraulic Press',
      'Industrial Refrigerators',
      'Kitchen Equipments',
      'Laboratory Equipment',
      'Lathe Machines',
      'Laundry Equipment',
      'Loaders',
      'Material Handling Equipments',
      'Packaging Machinery',
      'Paddle Dryer',
      'Panels',
      'Plastic Moulding Machine',
      'Poultry Farming Equipment',
      'Powder Coating Machines',
      'Rock Breakers',
      'Roller Mill',
      'Sewing machines',
      'Stabilizers',
      'Surgical Instruments',
      'Swimming Pool Equipment',
      'Tipper',
      'UPS',
      'Vending Machines',
      'Weighing Equipment',
      'Wood Working Machines',
    ],
  },
  {
    majorCategory: 'Retail Repair & Maintenance',
    minorCategories: [
      'Audio System Repair & Maintenance',
      'CCTV Repair & Maintenance',
      'Carpentary Repair & Maintenance',
      'Civil works Repair & Maintenance',
      'Electrical Repair & Maintenance',
      'Equipment Repair & Maintenance',
      'Fire Fighting Repair & Maintenance',
      'Flooring Repair & Maintenance',
      'HVAC Repair & Maintenance',
      'Light Fixtures Repair & Maintenance',
      'Mirror Repair & Maintenance',
      'Painting Repair & Maintenance',
      'Rolling Shutter Repair & Maintenance',
      'Shopfixtures Repair & Maintenance',
      'Signage Repair & Maintenance',
      'Visual Merchandising(VM) Repair & Maintenance',
    ],
  },
  {
    majorCategory: 'New Category-Product',
    minorCategories: [
      'Air Purifiers',
      'Automation & Controls',
      'Bakery & Kitchenware',
      'Cermaic Items',
      'Cleanroom Solutions',
      'Cold Storage',
      'Dairy Products',
      'Dehumidifiers',
      'Fencing',
      'Fertilizers',
      'Food & Beverages',
      'Furniture',
      'Gas Analizer & Monitors',
      'Geotextiles',
      'Glass',
      'HVAC',
      'Health Equipments',
      'Home Appliances',
      'House Keeping Materials',
      'Louvers',
      'Manhole covers',
      'Measuring Equipment',
      'Office & security Cabins',
      'Optical Products',
      'Personal Care & Cosmetics',
      'Petroleum Products',
      'Polymer Products',
      'Power press Machines',
      'Railway Products',
      'Renewable Energy',
      'Retail Fixtures',
      'Rubber and Tyre Machinery',
      'Scrap',
      'Sports Equipment',
      'Stationery',
      'Storage Racks',
      'Tarpaulin',
      'Tent House',
      'Textile and fabric',
      'Trophies',
      'Water Treatment Plants',
      'Water purifier',
    ],
  },
  {
    majorCategory: 'New Category-Service',
    minorCategories: [
      'Appliances Services',
      'Calibration Services',
      'Corrosion Protection',
      'Drone Surveys',
      'Electroplating Services',
      'Pollution Control',
      'Warehousing',
      'Waste Management',
    ],
  },
];

/** The leading major/minor pair, for assertions that just need a valid value. */
export const FIRST_MAJOR = CATEGORY_TAXONOMY_FIXTURE[0].majorCategory;
export const FIRST_MINOR = CATEGORY_TAXONOMY_FIXTURE[0].minorCategories[0];

export default CATEGORY_TAXONOMY_FIXTURE;
