import {
  SourcingModeDetail,
  RFQItem,
  AIBotFeedItem,
  VendorOpportunity,
  AuditLogEntry,
  AzureServiceHealth,
  SystemConfig,
  VendorEvaluationRecord,
  VendorEntry,
  BuyerAccount,
} from './types';

export interface MasterPlatformVendor {
  id: string;
  name: string;
  brandName: string;
  contactPerson: string;
  email: string;
  phone: string;
  gstin: string;
  panNumber: string;
  majorCategory: string;
  minorCategories: string[];
  location: string;
  rating: number;
  isVerified: boolean;
}

export const MASTER_PLATFORM_VENDORS: MasterPlatformVendor[] = [
  {
    id: 'mst-v-1',
    name: 'Apex Supplies Ltd.',
    brandName: 'Apex Industrial Dynamics',
    contactPerson: 'Rajesh Nair',
    email: 'rajesh@apexsupplies.in',
    phone: '+91 98201 44820',
    gstin: '27AAACA1928K1Z4',
    panNumber: 'AAACA1928K',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Pumps & Accessories', 'Compressors & Accessories', 'Machinery Parts'],
    location: 'Mumbai, MH',
    rating: 4.9,
    isVerified: true,
  },
  {
    id: 'mst-v-2',
    name: 'TechnoForce Engineering',
    brandName: 'TechnoForce Power',
    contactPerson: 'Sunita Reddy',
    email: 'sunita@technoforce.in',
    phone: '+91 87654 32109',
    gstin: '36AAACT9920P1Z8',
    panNumber: 'AAACT9920P',
    majorCategory: 'Engineering Spares - Electrical',
    minorCategories: ['Panels', 'Circuit Breakers', 'Transformers'],
    location: 'Hyderabad, TS',
    rating: 4.8,
    isVerified: true,
  },
  {
    id: 'mst-v-3',
    name: 'Delta Valve Systems Ltd.',
    brandName: 'DeltaFlow Industrial',
    contactPerson: 'Vikram Joshi',
    email: 'v.joshi@deltavalves.in',
    phone: '+91 98220 18492',
    gstin: '27AABCD3920M1Z8',
    panNumber: 'AABCD3920M',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Hoses, Valves & Fittings', 'Pipes & Pipe Fittings'],
    location: 'Pune, MH',
    rating: 4.8,
    isVerified: true,
  },
  {
    id: 'mst-v-4',
    name: 'Dynamic Flow Controls Pvt Ltd',
    brandName: 'Dynaflow Heavy',
    contactPerson: 'K. Senthil Nathan',
    email: 'senthil@dynamicflow.co.in',
    phone: '+91 94440 82910',
    gstin: '33AAACD8819L1Z2',
    panNumber: 'AAACD8819L',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Hoses, Valves & Fittings'],
    location: 'Chennai, TN',
    rating: 4.7,
    isVerified: true,
  },
  {
    id: 'mst-v-5',
    name: 'ElectroMech Pumps & Spares',
    brandName: 'ElectroMech Power',
    contactPerson: 'Anand Kulkarni',
    email: 'anand.k@electromechpumps.com',
    phone: '+91 98190 33491',
    gstin: '27AAECE4910P1Z4',
    panNumber: 'AAECE4910P',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Pumps & Accessories', 'Motors'],
    location: 'Mumbai, MH',
    rating: 4.6,
    isVerified: true,
  },
  {
    id: 'mst-v-6',
    name: 'Sigma Switchgears & Controls',
    brandName: 'Sigma Volt',
    contactPerson: 'Rajeev Singhania',
    email: 'tenders@sigmaswitchgears.com',
    phone: '+91 98110 55420',
    gstin: '09AAACS9918K1Z3',
    panNumber: 'AAACS9918K',
    majorCategory: 'Engineering Spares - Electrical',
    minorCategories: ['Panels', 'Circuit Breakers'],
    location: 'Noida, UP',
    rating: 4.5,
    isVerified: true,
  },
  {
    id: 'mst-v-7',
    name: 'Johnson Controls Roster Direct',
    brandName: 'Johnson Controls Building Tech',
    contactPerson: 'David Chen',
    email: 'david.chen@johnsoncontrols.com',
    phone: '+91 98110 22334',
    gstin: '27AAACJ4928A1Z0',
    panNumber: 'AAACJ4928A',
    majorCategory: 'Engineering Spares - Electrical',
    minorCategories: ['Controllers', 'Sensors'],
    location: 'Mumbai, MH',
    rating: 4.7,
    isVerified: true,
  },
];

export const INITIAL_BUYER_VENDORS: VendorEntry[] = [
  {
    id: 'v-1',
    name: 'Apex Supplies Ltd.',
    contactPerson: 'Rajesh Nair',
    phone: '+91 98201 44820',
    email: 'rajesh@apexsupplies.in',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Pumps & Accessories', 'Compressors & Accessories', 'Machinery Parts'],
    location: 'Mumbai, MH',
    rating: 4.9,
    source: 'buyer_manual',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    score: 95,
    evaluated: true,
    hasRecord: true,
    isExistingInDatabase: true,
    onboardingEmailStatus: 'delivered',
    onboardingEmailDispatchedAt: '2026-08-20 10:30 UTC',
    tempPassword: 'Apex@Procucev2026#',
    firstLoginCompleted: true,
    reminderCadence: 'every_3_days',
    nextReminderDate: '2026-09-01 (Day 3)',
    remindersSentCount: 0,
    addedByBuyerCompany: 'Larsen & Toubro Limited',
    addedByBuyerName: 'Rajesh Sharma (CPO)',
    profileCompletionStatus: 'completed',
    overlap: true,
  } as any,
  {
    id: 'v-2',
    name: 'Kiran Valve Industries',
    contactPerson: 'Amit Kumar',
    phone: '+91 97653 21098',
    email: 'amit@kiranvalves.com',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Hoses, Valves & Fittings', 'Pipes & Pipe Fittings'],
    location: 'Pune, MH',
    rating: 4.5,
    source: 'buyer_excel',
    status: 'CONDITIONAL / UNDER REVIEW',
    score: 72,
    evaluated: true,
    hasRecord: true,
    isExistingInDatabase: false,
    onboardingEmailStatus: 'sent',
    onboardingEmailDispatchedAt: '2026-08-28 09:15 UTC',
    tempPassword: 'Kiran@Temp8821#',
    firstLoginCompleted: false,
    reminderCadence: 'every_3_days',
    nextReminderDate: '2026-08-31 (Day 3)',
    remindersSentCount: 0,
    addedByBuyerCompany: 'Larsen & Toubro Limited',
    addedByBuyerName: 'Rajesh Sharma (CPO)',
    profileCompletionStatus: 'pending',
    overlap: false,
  } as any,
  {
    id: 'v-3',
    name: 'TechnoForce Engineering',
    contactPerson: 'Sunita Reddy',
    phone: '+91 87654 32109',
    email: 'sunita@technoforce.in',
    majorCategory: 'Engineering Spares - Electrical',
    minorCategories: ['Panels', 'Circuit Breakers', 'Transformers'],
    location: 'Hyderabad, TS',
    rating: 4.8,
    source: 'buyer_manual',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    score: 92,
    evaluated: true,
    hasRecord: true,
    isExistingInDatabase: true,
    onboardingEmailStatus: 'delivered',
    onboardingEmailDispatchedAt: '2026-08-22 14:20 UTC',
    tempPassword: 'Techno@Procucev#99',
    firstLoginCompleted: true,
    reminderCadence: 'every_3_days',
    nextReminderDate: '2026-09-01 (Day 3)',
    remindersSentCount: 0,
    addedByBuyerCompany: 'Larsen & Toubro Limited',
    addedByBuyerName: 'Rajesh Sharma (CPO)',
    profileCompletionStatus: 'completed',
    overlap: false,
  } as any,
  {
    id: 'v-4',
    name: 'Precision Pumps & Motors Pvt Ltd',
    contactPerson: 'Vikram Shah',
    phone: '+91 99876 54321',
    email: 'vikram@precisionpumps.co.in',
    majorCategory: 'Engineering Spares - Mechanical',
    minorCategories: ['Pumps & Accessories', 'Motors', 'Customised Parts'],
    location: 'Pune, MH',
    rating: 4.4,
    source: 'buyer_excel',
    status: 'REGISTERED / NOT EVALUATED',
    score: null,
    evaluated: false,
    hasRecord: false,
    isExistingInDatabase: false,
    onboardingEmailStatus: 'sent',
    onboardingEmailDispatchedAt: '2026-08-28 11:45 UTC',
    tempPassword: 'Pump@Welcome2026#',
    firstLoginCompleted: false,
    reminderCadence: 'every_3_days',
    nextReminderDate: '2026-08-31 (Day 3)',
    remindersSentCount: 0,
    addedByBuyerCompany: 'Larsen & Toubro Limited',
    addedByBuyerName: 'Rajesh Sharma (CPO)',
    profileCompletionStatus: 'pending',
    overlap: false,
  } as any,
  {
    id: 'v-5',
    name: 'CoolAir HVAC Systems',
    contactPerson: 'Priya Menon',
    phone: '+91 94321 67890',
    email: 'priya@coolairsys.com',
    majorCategory: 'CAPEX - Equipment & Machinery',
    minorCategories: ['Air Conditioners', 'Industrial Fans', 'Blowers'],
    location: 'Chennai, TN',
    rating: 4.6,
    source: 'buyer_manual',
    status: 'REGISTERED / NOT EVALUATED',
    score: null,
    evaluated: false,
    hasRecord: false,
    isExistingInDatabase: false,
    onboardingEmailStatus: 'sent',
    onboardingEmailDispatchedAt: '2026-08-27 16:30 UTC',
    tempPassword: 'HVAC@Temp7710#',
    firstLoginCompleted: false,
    reminderCadence: 'every_3_days',
    nextReminderDate: '2026-08-30 (Day 3)',
    remindersSentCount: 0,
    addedByBuyerCompany: 'Larsen & Toubro Limited',
    addedByBuyerName: 'Rajesh Sharma (CPO)',
    profileCompletionStatus: 'pending',
    overlap: false,
  } as any,
  {
    id: 'v-6',
    name: 'Everest Steel & Infra Structures',
    contactPerson: 'Harish Mehta',
    phone: '+91 98111 22334',
    email: 'harish@evereststeel.in',
    majorCategory: 'Civil Works',
    minorCategories: ['PEB Structure', 'Roofing Sheets', 'TMT BARS'],
    location: 'Ahmedabad, GJ',
    rating: 4.7,
    source: 'buyer_excel',
    status: 'REGISTERED / NOT EVALUATED',
    score: null,
    evaluated: false,
    hasRecord: false,
    isExistingInDatabase: false,
    onboardingEmailStatus: 'sent',
    onboardingEmailDispatchedAt: '2026-08-28 12:00 UTC',
    tempPassword: 'Steel@Procucev44#',
    firstLoginCompleted: false,
    reminderCadence: 'every_3_days',
    nextReminderDate: '2026-08-31 (Day 3)',
    remindersSentCount: 0,
    addedByBuyerCompany: 'Larsen & Toubro Limited',
    addedByBuyerName: 'Rajesh Sharma (CPO)',
    profileCompletionStatus: 'pending',
    overlap: false,
  } as any,
  {
    id: 'v-7',
    name: 'NetCore Enterprise IT Solutions',
    contactPerson: 'Ritu Deshmukh',
    phone: '+91 98765 44332',
    email: 'ritu@netcoreit.com',
    majorCategory: 'IT',
    minorCategories: ['Servers', 'Networking Equipment', 'Computer', 'Laptop'],
    location: 'Bangalore, KA',
    rating: 4.8,
    source: 'buyer_manual',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    score: 91,
    evaluated: true,
    hasRecord: true,
    overlap: false,
  } as any,
];

export const SOURCING_MODES: SourcingModeDetail[] = [
  {
    id: 'mode_1',
    code: 'Version 1',
    name: 'Version 1: Client Approved Vendors Only',
    shortLabel: 'Client Approved Pool',
    description: 'Restricted Private Roster - Dispatches RFQs exclusively to the pre-approved enterprise vendor master list.',
    badgeColor: '#074193',
  },
  {
    id: 'mode_2',
    code: 'Version 2',
    name: 'Version 2: Client + Procucev Vendors',
    shortLabel: 'Hybrid Sourced Pool',
    description: 'Hybrid Sourced Pool - Combines your trusted vendor roster with vetted Procucev high-performance suppliers for maximum price discovery.',
    badgeColor: '#00dbff',
  },
  {
    id: 'mode_3',
    code: 'Version 3',
    name: 'Version 3: AI Vendor Evaluation & Recommendation',
    shortLabel: 'AI Match (>80%)',
    description: 'AI Vendor Evaluation & Recommendation - Autonomous market scanning, OCR evaluation, and deep capability scoring for suppliers with >80% match.',
    badgeColor: '#ff4800',
  },
];

export const INITIAL_RFQS: RFQItem[] = [
  {
    id: 'rfq-00421',
    rfqNumber: 'RFQ-2026-00421',
    title: 'Centrifugal Water Pumps (500 GPM)',
    category: 'Mechanical / Fluid Dynamics',
    sourcingMode: 'mode_2',
    status: 'In Evaluation',
    quotesCount: 5,
    targetDeliveryDate: '2026-09-15',
    budget: 145000,
    createdAt: '2026-08-12 10:15:22',
    chasingActive: true,
    chaserMethod: 'Multi-Channel',
    aiScore: 94,
    source: 'email_gateway',
    sourceEmail: 'plant.procurement@lt-heavy.com',
    autoCirculated: true,
    extractedEntities: [
      {
        id: 'ent-1',
        itemName: 'Centrifugal Water Pump (500 GPM)',
        quantity: 12,
        unit: 'Units',
        targetDate: '2026-09-15',
        technicalSpecs: 'Stainless Steel Impeller (SS316), 15 HP TEFC Motor, ANSI Flanged, 150 PSI rating',
        confidence: 98.4,
        category: 'Engineering Spares - Mechanical',
        majorCategory: 'Engineering Spares - Mechanical',
        minorCategory: 'Pumps & Accessories',
      },
      {
        id: 'ent-2',
        itemName: 'Flanged Gate Valve (4-inch Class 150)',
        quantity: 24,
        unit: 'Units',
        targetDate: '2026-09-18',
        technicalSpecs: 'ASTM A216 WCB Cast Carbon Steel Body, 150# Raised Face Flange, Rising Stem',
        confidence: 96.2,
        category: 'Engineering Spares - Mechanical',
        majorCategory: 'Engineering Spares - Mechanical',
        minorCategory: 'Hoses, Valves & Fittings',
      },
    ],
    quotes: [
      {
        vendorId: 'v-101',
        vendorName: 'Vendor A (Kirloskar Flow Tech)',
        vendorCategory: 'Client List',
        unitPrice: 12400,
        totalPrice: 148800,
        leadTimeDays: 14,
        aiMatchScore: 78,
        isBestPrice: false,
        isPreferred: false,
        warrantyYears: 2,
        complianceStatus: 'Fully Compliant',
        paymentTerms: 'Net 30 Days',
        remarks: 'Standard OEM assembly. Direct warehouse shipment from Pune facility.',
      },
      {
        vendorId: 'v-102',
        vendorName: 'Vendor B (Flowserve India Pvt)',
        vendorCategory: 'Client List',
        unitPrice: 11800,
        totalPrice: 141600,
        leadTimeDays: 21,
        aiMatchScore: 82,
        isBestPrice: false,
        isPreferred: false,
        warrantyYears: 3,
        complianceStatus: 'Fully Compliant',
        paymentTerms: 'Net 45 Days',
        remarks: 'Premium cast alloy housing. Extended hydrostatic test report included.',
      },
      {
        vendorId: 'v-103',
        vendorName: 'Vendor C (Apex Supplies Ltd. - Procucev AI Rec)',
        vendorCategory: 'Procucev - AI Rec',
        unitPrice: 10950,
        totalPrice: 131400,
        leadTimeDays: 10,
        aiMatchScore: 94,
        isBestPrice: true,
        isPreferred: true,
        warrantyYears: 3,
        complianceStatus: 'Fully Compliant',
        paymentTerms: 'Net 30 Days (Pre-negotiated)',
        remarks: 'Top rated supplier in Procucev Network. Immediate stock dispatch available with certified ANSI compliance certificates.',
      },
    ],
    followUpData: {
      rfqNumber: 'RFQ-2026-00421',
      totalInvited: 5,
      respondedCount: 3,
      callStats: {
        total: 5,
        connected: 4,
        avgDuration: '1m 48s',
      },
      whatsappStats: {
        total: 5,
        delivered: 5,
        read: 4,
        replied: 3,
      },
      smsStats: {
        total: 5,
        delivered: 5,
        clicked: 3,
      },
      nextScheduledChaser: 'Today, 02:30 PM (Round 2 Escalation)',
      autoChasingEnabled: true,
      vendors: [
        {
          vendorId: 'v-103',
          vendorName: 'Apex Supplies Ltd.',
          phone: '+91 98201 44820',
          contactPerson: 'Rajesh Nair (Sales VP)',
          call: {
            status: 'completed',
            lastAttempt: '11:15 AM',
            duration: '2m 14s',
            summary: 'AI Voice Bot confirmed pricing & 10-day lead time commitment. Vendor acknowledged RFQ specs and agreed to terms.',
            transcriptSnippet: 'AI Bot: "Confirming 12 units SS316 500 GPM pump delivery to Navi Mumbai?" / Rajesh: "Yes, inventory verified, quotation submitted."',
          },
          whatsapp: {
            status: 'replied',
            lastAttempt: '11:20 AM',
            messagePreview: 'Bid submitted successfully via WhatsApp quick-link (Ref: QUO-APEX-992).',
            linkClicked: true,
          },
          sms: {
            status: 'clicked',
            lastAttempt: '10:00 AM',
            deliveryReport: 'Delivered (Airtel DLT verified)',
          },
          overallStatus: 'Responded',
          lastInteraction: '11:20 AM',
          attemptsCount: 2,
          bidStatus: 'Submitted',
        },
        {
          vendorId: 'v-101',
          vendorName: 'Kirloskar Flow Tech',
          phone: '+91 97654 11200',
          contactPerson: 'Amit Kirloskar',
          call: {
            status: 'completed',
            lastAttempt: '08:35 AM',
            duration: '1m 32s',
            summary: 'Vendor indicated price submitted for $12,400/unit with standard 2-year warranty.',
            transcriptSnippet: 'AI Bot: "Following up on RFQ-2026-00421 quote submission" / Amit: "Proposal uploaded via the portal link."',
          },
          whatsapp: {
            status: 'replied',
            lastAttempt: '08:40 AM',
            messagePreview: 'Direct quotation link accessed and line-item table filled.',
            linkClicked: true,
          },
          sms: {
            status: 'delivered',
            lastAttempt: '08:00 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Responded',
          lastInteraction: '08:40 AM',
          attemptsCount: 1,
          bidStatus: 'Submitted',
        },
        {
          vendorId: 'v-102',
          vendorName: 'Flowserve India Pvt',
          phone: '+91 98400 66321',
          contactPerson: 'Priya Sundaram',
          call: {
            status: 'connected',
            lastAttempt: '09:50 AM',
            duration: '1m 15s',
            summary: 'Priya requested payment term clarification. Confirmed bid submission by 3 PM.',
            transcriptSnippet: 'Priya: "We are adjusting hydrostatic test certificates before final submission."',
          },
          whatsapp: {
            status: 'read',
            lastAttempt: '09:55 AM',
            messagePreview: 'Reminder sent: RFQ closes in 24h. Click to submit: portal.procucev.com/bid/00421',
            linkClicked: true,
          },
          sms: {
            status: 'delivered',
            lastAttempt: '09:00 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Follow-up Active',
          lastInteraction: '09:55 AM',
          attemptsCount: 2,
          bidStatus: 'In Progress',
        },
        {
          vendorId: 'v-108',
          vendorName: 'Grundfos Industrial Systems',
          phone: '+91 99203 77410',
          contactPerson: 'Vikram Mehta',
          call: {
            status: 'voicemail',
            lastAttempt: '10:30 AM',
            duration: '0m 45s',
            summary: 'Left automated AI voicemail reminder on direct sales line regarding urgent 24h deadline.',
            transcriptSnippet: 'AI Voice Dispatch: "Automated reminder from Procucev Enterprise regarding RFQ-2026-00421..."',
          },
          whatsapp: {
            status: 'delivered',
            lastAttempt: '10:32 AM',
            messagePreview: 'Action Required: Procucev Buyer has prioritized RFQ-2026-00421.',
            linkClicked: false,
          },
          sms: {
            status: 'delivered',
            lastAttempt: '10:30 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Awaiting Bid',
          lastInteraction: '10:32 AM',
          attemptsCount: 3,
          bidStatus: 'Pending',
        },
        {
          vendorId: 'v-109',
          vendorName: 'WPIL Pumps Ltd',
          phone: '+91 98311 90223',
          contactPerson: 'Sanjoy Mukherjee',
          call: {
            status: 'scheduled',
            lastAttempt: '09:10 AM',
            duration: '0m 28s',
            summary: 'Vendor requested AI callback at 2:30 PM due to morning client board meeting.',
          },
          whatsapp: {
            status: 'read',
            lastAttempt: '09:15 AM',
            messagePreview: 'Interactive RFQ Brief sent. Read at 09:18 AM.',
            linkClicked: false,
          },
          sms: {
            status: 'delivered',
            lastAttempt: '09:00 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Follow-up Active',
          lastInteraction: '09:18 AM',
          attemptsCount: 1,
          bidStatus: 'Pending',
        },
      ],
    },
  },
  {
    id: 'rfq-00420',
    rfqNumber: 'RFQ-2026-00420',
    title: 'HVAC Microprocessor Control Units',
    category: 'Building Automation & HVAC',
    sourcingMode: 'mode_1',
    status: 'In Evaluation',
    quotesCount: 3,
    targetDeliveryDate: '2026-09-20',
    budget: 95000,
    createdAt: '2026-08-14 09:30:00',
    chasingActive: true,
    chaserMethod: 'Multi-Channel',
    aiScore: 86,
    source: 'web_portal',
    sourceFileName: 'BOQ_HVAC_Microprocessor_DDC.xlsx',
    autoCirculated: false,
    extractedEntities: [
      {
        id: 'ent-3',
        itemName: 'Direct Digital Controller (DDC-400)',
        quantity: 8,
        unit: 'Units',
        targetDate: '2026-09-20',
        technicalSpecs: 'BACnet IP / MS-TP compatible, 32 Universal I/O, Modbus RTU interface',
        confidence: 99.1,
        category: 'Engineering Spares - Electrical',
        majorCategory: 'Engineering Spares - Electrical',
        minorCategory: 'Controllers',
      },
    ],
    quotes: [
      {
        vendorId: 'v-104',
        vendorName: 'Johnson Controls Roster',
        vendorCategory: 'Client List',
        unitPrice: 8400,
        totalPrice: 67200,
        leadTimeDays: 18,
        aiMatchScore: 88,
        isBestPrice: true,
        isPreferred: true,
        warrantyYears: 2,
        complianceStatus: 'Fully Compliant',
        paymentTerms: 'Net 30 Days',
        remarks: 'Standard factory calibrated units.',
      },
      {
        vendorId: 'v-105',
        vendorName: 'Honeywell Solutions Direct',
        vendorCategory: 'Client List',
        unitPrice: 8900,
        totalPrice: 71200,
        leadTimeDays: 14,
        aiMatchScore: 84,
        isBestPrice: false,
        isPreferred: false,
        warrantyYears: 2,
        complianceStatus: 'Fully Compliant',
        paymentTerms: 'Net 30 Days',
        remarks: 'Includes firmware v4.2 upgrade licence.',
      },
    ],
    followUpData: {
      rfqNumber: 'RFQ-2026-00420',
      totalInvited: 3,
      respondedCount: 2,
      callStats: {
        total: 3,
        connected: 3,
        avgDuration: '1m 20s',
      },
      whatsappStats: {
        total: 3,
        delivered: 3,
        read: 3,
        replied: 2,
      },
      smsStats: {
        total: 3,
        delivered: 3,
        clicked: 2,
      },
      nextScheduledChaser: 'Tomorrow, 10:00 AM',
      autoChasingEnabled: true,
      vendors: [
        {
          vendorId: 'v-104',
          vendorName: 'Johnson Controls Roster',
          phone: '+91 98110 22334',
          contactPerson: 'David Chen',
          call: {
            status: 'completed',
            lastAttempt: 'Yesterday, 04:10 PM',
            duration: '1m 40s',
            summary: 'Call connected with OEM sales desk. Confirmed line-item price of $8,400.',
          },
          whatsapp: {
            status: 'replied',
            lastAttempt: 'Yesterday, 04:30 PM',
            messagePreview: 'Quote uploaded and verified against BACnet IP specs.',
            linkClicked: true,
          },
          sms: {
            status: 'clicked',
            lastAttempt: 'Yesterday, 03:00 PM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Responded',
          lastInteraction: 'Yesterday, 04:30 PM',
          attemptsCount: 1,
          bidStatus: 'Submitted',
        },
        {
          vendorId: 'v-105',
          vendorName: 'Honeywell Solutions Direct',
          phone: '+91 98220 55667',
          contactPerson: 'Anjali Sharma',
          call: {
            status: 'completed',
            lastAttempt: 'Yesterday, 05:15 PM',
            duration: '1m 10s',
            summary: 'Vendor confirmed firmware v4.2 compatibility and uploaded pricing.',
          },
          whatsapp: {
            status: 'replied',
            lastAttempt: 'Yesterday, 05:40 PM',
            messagePreview: 'Quotation submitted with technical datasheet attached.',
            linkClicked: true,
          },
          sms: {
            status: 'delivered',
            lastAttempt: 'Yesterday, 03:00 PM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Responded',
          lastInteraction: 'Yesterday, 05:40 PM',
          attemptsCount: 1,
          bidStatus: 'Submitted',
        },
        {
          vendorId: 'v-110',
          vendorName: 'Siemens Building Tech',
          phone: '+91 98450 77889',
          contactPerson: 'Karan Malhotra',
          call: {
            status: 'connected',
            lastAttempt: 'Today, 09:30 AM',
            duration: '0m 55s',
            summary: 'Sales manager stated they are compiling controller stock availability.',
          },
          whatsapp: {
            status: 'read',
            lastAttempt: 'Today, 09:35 AM',
            messagePreview: 'Direct portal upload link dispatched.',
            linkClicked: true,
          },
          sms: {
            status: 'delivered',
            lastAttempt: 'Today, 09:00 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Follow-up Active',
          lastInteraction: 'Today, 09:35 AM',
          attemptsCount: 2,
          bidStatus: 'In Progress',
        },
      ],
    },
  },
  {
    id: 'rfq-00418',
    rfqNumber: 'RFQ-2026-00418',
    title: 'LV Electrical Switchgear & Control Panels',
    category: 'Electrical Infrastructure',
    sourcingMode: 'mode_3',
    status: 'AI Recommended',
    quotesCount: 8,
    targetDeliveryDate: '2026-09-30',
    budget: 320000,
    createdAt: '2026-08-10 14:20:10',
    chasingActive: false,
    chaserMethod: 'Multi-Channel',
    aiScore: 96,
    source: 'email_gateway',
    sourceEmail: 'electrical.lead@lt-heavy.com',
    autoCirculated: true,
    extractedEntities: [
      {
        id: 'ent-4',
        itemName: 'Form 4b Low Voltage Switchboard 4000A',
        quantity: 2,
        unit: 'Sets',
        targetDate: '2026-09-30',
        technicalSpecs: 'IEC 61439-2 certified, 65kA 1-sec fault withstand, IP54 enclosure',
        confidence: 97.8,
        category: 'Engineering Spares - Electrical',
        majorCategory: 'Engineering Spares - Electrical',
        minorCategory: 'Panels',
      },
    ],
    quotes: [
      {
        vendorId: 'v-106',
        vendorName: 'Schneider Electric Certified Panel Builder',
        vendorCategory: 'Procucev - AI Rec',
        unitPrice: 142000,
        totalPrice: 284000,
        leadTimeDays: 24,
        aiMatchScore: 96,
        isBestPrice: true,
        isPreferred: true,
        warrantyYears: 5,
        complianceStatus: 'Fully Compliant',
        paymentTerms: 'Net 45 Days',
        remarks: 'Highest AI match rating. Verified test certificates for arc fault containment.',
      },
      {
        vendorId: 'v-107',
        vendorName: 'L&T Switchgear Division',
        vendorCategory: 'Client List',
        unitPrice: 151000,
        totalPrice: 302000,
        leadTimeDays: 28,
        aiMatchScore: 89,
        isBestPrice: false,
        isPreferred: false,
        warrantyYears: 3,
        complianceStatus: 'Fully Compliant',
        paymentTerms: 'Net 30 Days',
        remarks: 'Standard modular enclosure design.',
      },
    ],
    followUpData: {
      rfqNumber: 'RFQ-2026-00418',
      totalInvited: 8,
      respondedCount: 8,
      callStats: {
        total: 8,
        connected: 8,
        avgDuration: '2m 05s',
      },
      whatsappStats: {
        total: 8,
        delivered: 8,
        read: 8,
        replied: 8,
      },
      smsStats: {
        total: 8,
        delivered: 8,
        clicked: 8,
      },
      nextScheduledChaser: 'All Bids In • Chasing Complete',
      autoChasingEnabled: false,
      vendors: [
        {
          vendorId: 'v-106',
          vendorName: 'Schneider Electric Certified Builder',
          phone: '+91 98200 88990',
          contactPerson: 'Alok Verma',
          call: {
            status: 'completed',
            lastAttempt: '18-Aug, 11:00 AM',
            duration: '2m 45s',
            summary: 'Technical capability verified. 5-year warranty & IEC 61439-2 certification confirmed by panel builder.',
          },
          whatsapp: {
            status: 'replied',
            lastAttempt: '18-Aug, 11:30 AM',
            messagePreview: 'Complete engineering drawing and pricing breakdown submitted.',
            linkClicked: true,
          },
          sms: {
            status: 'clicked',
            lastAttempt: '18-Aug, 10:00 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Responded',
          lastInteraction: '18-Aug, 11:30 AM',
          attemptsCount: 1,
          bidStatus: 'Submitted',
        },
        {
          vendorId: 'v-107',
          vendorName: 'L&T Switchgear Division',
          phone: '+91 98190 33445',
          contactPerson: 'Suresh Menon',
          call: {
            status: 'completed',
            lastAttempt: '18-Aug, 02:15 PM',
            duration: '1m 50s',
            summary: 'L&T submitted formal proposal ($151,000/set).',
          },
          whatsapp: {
            status: 'replied',
            lastAttempt: '18-Aug, 02:40 PM',
            messagePreview: 'Quotation uploaded to buyer portal.',
            linkClicked: true,
          },
          sms: {
            status: 'delivered',
            lastAttempt: '18-Aug, 10:00 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Responded',
          lastInteraction: '18-Aug, 02:40 PM',
          attemptsCount: 1,
          bidStatus: 'Submitted',
        },
      ],
    },
  },
  {
    id: 'rfq-00425',
    rfqNumber: 'RFQ-2026-00425',
    title: 'High Pressure Cryogenic Valves',
    category: 'Specialized Valves',
    sourcingMode: 'mode_2',
    status: 'Parsing',
    quotesCount: 0,
    targetDeliveryDate: '2026-10-10',
    budget: 82000,
    createdAt: '2026-08-19 09:10:00',
    chasingActive: true,
    chaserMethod: 'Multi-Channel',
    extractedEntities: [
      {
        id: 'ent-5',
        itemName: 'Cryogenic Globe Valve 2-inch 600#',
        quantity: 16,
        unit: 'Units',
        targetDate: '2026-10-10',
        technicalSpecs: 'Extended bonnet, Stainless Steel 316L, -196°C rated, ASME B16.34',
        confidence: 94.2,
        category: 'Cryogenics',
      },
    ],
    quotes: [],
    followUpData: {
      rfqNumber: 'RFQ-2026-00425',
      totalInvited: 4,
      respondedCount: 0,
      callStats: {
        total: 4,
        connected: 2,
        avgDuration: '0m 45s',
      },
      whatsappStats: {
        total: 4,
        delivered: 4,
        read: 2,
        replied: 0,
      },
      smsStats: {
        total: 4,
        delivered: 4,
        clicked: 1,
      },
      nextScheduledChaser: 'Today, 03:00 PM (Initial Vendor Outreach)',
      autoChasingEnabled: true,
      vendors: [
        {
          vendorId: 'v-111',
          vendorName: 'Microfinish Valves Pvt',
          phone: '+91 98220 11990',
          contactPerson: 'Nitin Sawant',
          call: {
            status: 'connected',
            lastAttempt: 'Today, 10:15 AM',
            duration: '0m 50s',
            summary: 'Vendor sales team notified about cryogenic valve RFQ specs. Reviewing BOQ.',
          },
          whatsapp: {
            status: 'read',
            lastAttempt: 'Today, 10:20 AM',
            messagePreview: 'New RFQ Ingestion: High Pressure Cryogenic Valves (16 Units).',
            linkClicked: true,
          },
          sms: {
            status: 'delivered',
            lastAttempt: 'Today, 10:10 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Follow-up Active',
          lastInteraction: 'Today, 10:20 AM',
          attemptsCount: 1,
          bidStatus: 'In Progress',
        },
        {
          vendorId: 'v-112',
          vendorName: 'L&T Valves Manufacturing',
          phone: '+91 98401 22334',
          contactPerson: 'Gopal Krishnan',
          call: {
            status: 'voicemail',
            lastAttempt: 'Today, 10:18 AM',
            duration: '0m 35s',
            summary: 'Left AI automated voice notice on Chennai office line.',
          },
          whatsapp: {
            status: 'delivered',
            lastAttempt: 'Today, 10:20 AM',
            messagePreview: 'RFQ Invitation for cryogenic valves dispatch.',
            linkClicked: false,
          },
          sms: {
            status: 'delivered',
            lastAttempt: 'Today, 10:10 AM',
            deliveryReport: 'Delivered',
          },
          overallStatus: 'Follow-up Active',
          lastInteraction: 'Today, 10:20 AM',
          attemptsCount: 1,
          bidStatus: 'Pending',
        },
      ],
    },
  },
  {
    id: 'rfq-00426',
    rfqNumber: 'RFQ-2026-00426',
    title: 'Seamless Carbon Steel Heavy Wall Pipes',
    category: 'Piping & Structural',
    sourcingMode: 'mode_1',
    status: 'Parsing',
    quotesCount: 0,
    targetDeliveryDate: '2026-10-15',
    budget: 190000,
    createdAt: '2026-08-19 10:05:00',
    chasingActive: false,
    extractedEntities: [
      {
        id: 'ent-6',
        itemName: 'ASTM A106 Grade B Pipe 8-inch SCH 80',
        quantity: 480,
        unit: 'Meters',
        targetDate: '2026-10-15',
        technicalSpecs: 'Seamless carbon steel, Hot finished, Beveled ends, NACE MR0175 compliant',
        confidence: 95.0,
        category: 'Piping',
      },
    ],
    quotes: [],
    followUpData: {
      rfqNumber: 'RFQ-2026-00426',
      totalInvited: 3,
      respondedCount: 0,
      callStats: {
        total: 3,
        connected: 1,
        avgDuration: '0m 30s',
      },
      whatsappStats: {
        total: 3,
        delivered: 3,
        read: 1,
        replied: 0,
      },
      smsStats: {
        total: 3,
        delivered: 3,
        clicked: 0,
      },
      nextScheduledChaser: 'Scheduled upon OCR validation complete',
      autoChasingEnabled: false,
      vendors: [
        {
          vendorId: 'v-113',
          vendorName: 'Jindal Saw Piping',
          phone: '+91 98100 44556',
          contactPerson: 'Harsh Vardhan',
          call: {
            status: 'scheduled',
            lastAttempt: 'Today, 10:30 AM',
            summary: 'Queued for automated dispatch after OCR schema signoff.',
          },
          whatsapp: {
            status: 'pending',
            lastAttempt: 'Queued',
            messagePreview: 'Draft RFQ payload ready.',
          },
          sms: {
            status: 'pending',
            lastAttempt: 'Queued',
          },
          overallStatus: 'Pending',
          lastInteraction: 'Today, 10:30 AM',
          attemptsCount: 0,
          bidStatus: 'Pending',
        },
      ],
    },
  },
];

export const INITIAL_AI_FEED: AIBotFeedItem[] = [
  {
    id: 'feed-call-1',
    timestamp: '11:32 AM',
    timeAgo: '4 mins ago',
    type: 'call',
    channel: 'call',
    title: 'AI Voice Call Connected & Verified',
    message: 'AI Voice Bot completed 2m 14s phone conversation with Apex Supplies Ltd. (+91 98201 44820). Confirmed delivery timeline & technical compliance for RFQ-2026-00421.',
    recipient: 'Apex Supplies Ltd. (Rajesh Nair)',
    rfqNumber: 'RFQ-2026-00421',
    status: 'completed',
    channelDetails: {
      duration: '2m 14s',
      transcriptSummary: 'Vendor verified inventory of 12 units SS316 pump, agreed to 10-day lead time commitment.',
      actionOutcome: 'Quote uploaded via instant link',
    },
  },
  {
    id: 'feed-wa-1',
    timestamp: '11:20 AM',
    timeAgo: '16 mins ago',
    type: 'whatsapp',
    channel: 'whatsapp',
    title: 'WhatsApp Interactive Prompt Read',
    message: 'Automated WhatsApp chaser read by Apex Supplies Ltd. for RFQ-2026-00421. 1-click bid submission link was accessed.',
    recipient: 'Apex Supplies Ltd. (+91 98201 44820)',
    rfqNumber: 'RFQ-2026-00421',
    status: 'read',
    channelDetails: {
      deliveryTimestamp: '11:18 AM',
      actionOutcome: 'Bid portal link clicked',
    },
  },
  {
    id: 'feed-sms-1',
    timestamp: '11:05 AM',
    timeAgo: '31 mins ago',
    type: 'sms',
    channel: 'sms',
    title: 'Automated SMS Urgent Alert Delivered',
    message: 'Priority SMS broadcast dispatched to 5 vendor sales desks for RFQ-2026-00421. Carrier DLT delivery status: 100% delivered.',
    recipient: '5 Invited Vendors Pool',
    rfqNumber: 'RFQ-2026-00421',
    status: 'delivered',
    channelDetails: {
      actionOutcome: '5 of 5 SMS Delivered via DLT gateway',
    },
  },
  {
    id: 'feed-call-2',
    timestamp: '10:50 AM',
    timeAgo: '46 mins ago',
    type: 'call',
    channel: 'call',
    title: 'AI Voice Bot Scheduled Callback',
    message: 'AI Voice agent attempted phone outreach to WPIL Pumps (+91 98311 90223). Vendor requested automated callback at 2:30 PM.',
    recipient: 'WPIL Pumps Ltd. (Sanjoy Mukherjee)',
    rfqNumber: 'RFQ-2026-00421',
    status: 'connected',
    channelDetails: {
      duration: '0m 28s',
      transcriptSummary: 'Vendor in client meeting, requested scheduled callback at 2:30 PM.',
      actionOutcome: 'Callback scheduled for 14:30',
    },
  },
  {
    id: 'feed-2',
    timestamp: '10:45 AM',
    timeAgo: '51 mins ago',
    type: 'scoring',
    title: 'Autonomous AI Scoring Completed',
    message: 'AI Evaluation Matrix synthesized 8 vendor line-item bids for RFQ-2026-00418. Match score calculated at 96% for preferred supplier.',
    rfqNumber: 'RFQ-2026-00418',
    status: 'completed',
  },
  {
    id: 'feed-wa-2',
    timestamp: '09:55 AM',
    timeAgo: '1.5 hours ago',
    type: 'whatsapp',
    channel: 'whatsapp',
    title: 'WhatsApp Reminder Delivered to Flowserve',
    message: 'Direct WhatsApp chasing message delivered to Flowserve India Pvt. Vendor confirmed bid preparation is in progress.',
    recipient: 'Flowserve India Pvt (+91 98400 66321)',
    rfqNumber: 'RFQ-2026-00421',
    status: 'read',
  },
  {
    id: 'feed-3',
    timestamp: '09:15 AM',
    timeAgo: '2.2 hours ago',
    type: 'ingestion',
    title: 'BOQ Document Ingestion via Email',
    message: 'Ingested raw Excel BOQ attachment received via client@procucev.com. OCR parsed 2 line-item entities with 98.4% confidence.',
    recipient: 'client@procucev.com',
    rfqNumber: 'RFQ-2026-00425',
    status: 'completed',
  },
  {
    id: 'feed-4',
    timestamp: '08:40 AM',
    timeAgo: '3 hours ago',
    type: 'whatsapp',
    channel: 'whatsapp',
    title: 'Bid Submitted via WhatsApp Bot Link',
    message: 'Kirloskar Flow Tech submitted verified line-item quotation ($12,400/unit) for RFQ-2026-00421.',
    recipient: 'Kirloskar Flow Tech',
    rfqNumber: 'RFQ-2026-00421',
    status: 'completed',
  },
  {
    id: 'feed-5',
    timestamp: '08:10 AM',
    timeAgo: '3.5 hours ago',
    type: 'escalation',
    title: 'Automated Chasing Escalation Rule Triggered',
    message: 'Multi-channel chasing threshold (24h) approached for RFQ-2026-00422. Auto-escalated to Category Manager queue with voice/WA logs.',
    rfqNumber: 'RFQ-2026-00422',
    status: 'completed',
  },
];

export const INITIAL_VENDOR_OPPORTUNITIES: VendorOpportunity[] = [
  {
    id: 'opp-1',
    rfqNumber: 'RFQ-2026-00421',
    title: 'Centrifugal Water Pumps (500 GPM) & Flanged Valves',
    buyer: 'Procucev Global Client (Energy & Utilities Division)',
    deadline: '2026-08-25',
    daysRemaining: 1,
    type: 'direct_invitation',
    estimatedValue: '$130,000 - $150,000',
    deliveryLocation: 'Navi Mumbai Industrial Zone / CIF Site',
    status: 'pending_bid',
    lineItems: [
      {
        id: 'li-1',
        description: 'Centrifugal Water Pump 500 GPM (15 HP Motor, ANSI Flanged)',
        quantity: 12,
        unitPrice: 10950,
        leadTimeDays: 10,
        uploadedDocument: 'Datasheet_Pump_500GPM_Apex.pdf',
        complianceDoc: 'ANSI_B73_Compliance_Cert.pdf',
        marketBandStatus: 'optimal',
        paymentTerms: 'Net 30 Days',
      },
      {
        id: 'li-2',
        description: 'Flanged Gate Valve 4-inch Class 150 (ASTM A216 WCB)',
        quantity: 24,
        unitPrice: 850,
        leadTimeDays: 5,
        uploadedDocument: 'Datasheet_GateValve_4in.pdf',
        complianceDoc: 'API_600_Inspection_Report.pdf',
        marketBandStatus: 'optimal',
        paymentTerms: 'Net 30 Days',
      },
    ],
  },
  {
    id: 'opp-2',
    rfqNumber: 'RFQ-2026-00420',
    title: 'HVAC Microprocessor Digital Control Systems',
    buyer: 'Procucev Real Estate & Infrastructure Consortium',
    deadline: '2026-08-28',
    daysRemaining: 4,
    type: 'direct_invitation',
    deliveryLocation: 'Bengaluru Tech Park Phase 2',
    status: 'pending_bid',
    lineItems: [
      {
        id: 'li-3',
        description: 'BACnet IP Direct Digital Controller DDC-400',
        quantity: 8,
        unitPrice: 8200,
        leadTimeDays: 12,
        marketBandStatus: 'optimal',
        paymentTerms: 'Net 30 Days',
      },
    ],
  },
  {
    id: 'opp-3',
    rfqNumber: 'RFQ-2026-00415',
    title: 'Structural High-Tensile Steel Beams & Columns (IS 2062 E350)',
    buyer: 'Procucev Network Marketplace',
    deadline: '2026-09-05',
    daysRemaining: 12,
    type: 'network_marketplace',
    deliveryLocation: 'Mumbai Port Logistics Terminal',
    status: 'pending_bid',
    lineItems: [
      {
        id: 'li-4',
        description: 'Heavy Structural H-Beams 300x300mm',
        quantity: 150,
        unitPrice: 1600,
        leadTimeDays: 15,
        marketBandStatus: 'optimal',
        paymentTerms: 'LC at sight / Net 30',
      },
    ],
  },
];

export const INITIAL_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'aud-101',
    timestamp: '2026-08-19 11:30:10 UTC',
    user: 'client@procucev.com (Enterprise Approver)',
    action: 'Approved PO Generation & Dispatched Contract for RFQ-2026-00421 ($131,400.00)',
    rfqNumber: 'RFQ-2026-00421',
    shaSignature: 'c7d1e3a985f621b0e49c812d4a7f55e0921bc3d49f018a7c2b53e6144f5592a1',
    status: 'VERIFIED',
    ipAddress: '104.42.189.44',
  },
  {
    id: 'aud-102',
    timestamp: '2026-08-19 11:02:45 UTC',
    user: 'vendor@apex.com (Apex Supplies Ltd.)',
    action: 'Submitted Line-Item Quotation & Technical Compliance Sheet ($10,950/unit)',
    rfqNumber: 'RFQ-2026-00421',
    shaSignature: 'f4e2b09a41c2847d819e652a901bb432c7104f981e7d824a0b25c8908a9011de',
    status: 'VERIFIED',
    ipAddress: '49.36.120.18',
  },
  {
    id: 'aud-103',
    timestamp: '2026-08-19 10:15:22 UTC',
    user: 'client@procucev.com (Enterprise Buyer)',
    action: 'Created RFQ-2026-00421 (Mode 2: Hybrid Sourced Pool Selected)',
    rfqNumber: 'RFQ-2026-00421',
    shaSignature: 'a8f9c10427de83f5b01859c240938b21ca52093e4f1837d92840ac3b210087fe',
    status: 'VERIFIED',
    ipAddress: '104.42.189.44',
  },
  {
    id: 'aud-104',
    timestamp: '2026-08-19 09:15:00 UTC',
    user: 'ai-engine@procucev.internal (Azure Function)',
    action: 'OCR Document Ingestion completed with 98.4% entity confidence',
    rfqNumber: 'RFQ-2026-00425',
    shaSignature: '2b73f8a01948ce7139a04f21e548d901a5b820cd3948ef01746201ba8314ff90',
    status: 'VERIFIED',
    ipAddress: '10.0.4.12',
  },
  {
    id: 'aud-105',
    timestamp: '2026-08-18 16:40:12 UTC',
    user: 'catmanager@procucev.com (Category Manager)',
    action: 'Executed Global Override: Batch WhatsApp Follow-up to 8 non-responsive vendors',
    rfqNumber: 'RFQ-2026-00418',
    shaSignature: '8401de91bc44837a0129fec8294710bc820173849182acdf820194bc029184ef',
    status: 'VERIFIED',
    ipAddress: '14.139.112.5',
  },
];

export const INITIAL_AZURE_HEALTH: AzureServiceHealth[] = [
  {
    service: 'Azure SQL Database (Master Ledger)',
    status: 'ONLINE',
    latency: '0.02s',
    uptime: '99.99%',
    details: 'Read/Write replicas synchronized. Automated Point-in-Time recovery active.',
  },
  {
    service: 'Azure Cosmos DB (RFQ & Entity Metadata)',
    status: 'HEALTHY',
    latency: '4ms',
    uptime: '100.00%',
    details: 'Multi-region distributed read with single-digit millisecond latency.',
  },
  {
    service: 'Azure Blob Storage (BOQs, Datasheets & POs)',
    status: 'ONLINE',
    latency: '12ms',
    uptime: '99.98%',
    details: 'Hot tier GRS replication. AES-256 server-side encryption enabled.',
  },
  {
    service: 'Azure Active Directory (Entra ID SSO & MFA)',
    status: 'ONLINE',
    latency: '18ms',
    uptime: '99.99%',
    details: 'SAML 2.0 / OIDC federated authentication for client@procucev.com.',
  },
];

export const INITIAL_SYSTEM_CONFIG: SystemConfig = {
  ollamaModel: 'Llama 3 (8B Instruct)',
  ollamaActive: true,
  ocrExtractionThreshold: 85,
  whatsappAutoChaser: true,
  escalationIntervalHours: 24,
  azureDbBackupFrequency: 'Continuous',
  rbacEnforced: true,
};

export const INITIAL_VENDOR_EVALUATIONS: VendorEvaluationRecord[] = [
  {
    id: 'eval-101',
    vendorId: 'v-1',
    vendorName: 'Apex Supplies Ltd.',
    contactPerson: 'Rajesh Nair',
    email: 'rajesh@apexsupplies.in',
    phone: '+91 98201 44820',
    category: 'Heavy Mechanical & Fluid Dynamics',
    submissionDate: '2026-08-18 14:30 UTC',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    overallScore: 95,
    systemAction: 'AUTOMATIC DIRECT RFQ DISPATCH TO VENDOR INBOX. 24/24 mandatory attachments verified via AI OCR engine. Vendor added to Mode 3 active bidding roster.',
    moduleScores: {
      commercial: { score: 4.75, maxScore: 5, weight: 25, weightedScore: 23.75, remarks: 'Commercial terms align well with enterprise cash-flow requirements. Agreed to Net 60 payment terms & 12M rate contract.' },
      technical: { score: 4.75, maxScore: 5, weight: 15, weightedScore: 14.25, remarks: 'Technical capabilities meet required specifications for precision manufacturing. Robotic CNC lines & NABL lab confirmed.' },
      quality: { score: 5.0, maxScore: 5, weight: 20, weightedScore: 20.0, remarks: 'Excellent quality control systems with low historical defect rates (280 PPM) & 24M warranty.' },
      delivery: { score: 4.5, maxScore: 5, weight: 20, weightedScore: 18.0, remarks: 'Operational capacity is strong (74% capacity); verified average OTIF 92.4% past 4 quarters.' },
      financial: { score: 5.0, maxScore: 5, weight: 10, weightedScore: 10.0, remarks: 'Healthy financial profile with high liquidity (1.82 current ratio) and low CRISIL A+ credit risk.' },
      governance: { score: 4.5, maxScore: 5, weight: 10, weightedScore: 9.0, remarks: 'Robust governance and compliance; GSTIN/PAN verified; ISO 45001 renewal flagged for routine tracking.' },
    },
    documents: [
      { id: 'doc-m1-1', name: 'Terms_Net60.pdf', type: 'Payment Terms Agreement', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m1-2', name: 'Rate_Contract_Agreement_12Mo.pdf', type: 'Fixed Rate Agreement', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m1-3', name: 'Freight_Policy.pdf', type: 'Freight Schedule', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m1-4', name: 'Volume_Discount_Matrix_Tier.xlsx', type: 'Discount Matrix', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m2-1', name: 'Technical_BOQ_Compliance_Datasheet.pdf', type: 'BOQ Specs', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m2-2', name: 'Factory_Equipment_Automation_Log.pdf', type: 'Equipment Log', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m2-3', name: 'NABL_Lab_Accreditation_Certificate.pdf', type: 'NABL Lab Cert', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m2-4', name: 'Technical_Service_SLA_Agreement.pdf', type: 'Service SLA', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m3-1', name: 'ISO_9001_TUV_Certificate.pdf', type: 'ISO 9001:2015 Cert', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m3-2', name: 'Historical_12M_Quality_Defect_Log.pdf', type: 'Defect History', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m3-3', name: 'Enterprise_Warranty_Policy_24Mo.pdf', type: 'Warranty Policy', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m3-4', name: 'RFID_Batch_Traceability_Manual.pdf', type: 'RFID Traceability', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m4-1', name: '4_Quarter_OTIF_Audit_Report.pdf', type: 'OTIF Audit', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m4-2', name: 'Production_SLA_Timeline_Doc.pdf', type: 'Production SLA', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m4-3', name: 'Plant_Capacity_Utilization_Audit.pdf', type: 'Capacity Audit', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m4-4', name: 'Business_Continuity_Plan_BCP.pdf', type: 'BCP Plan', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m5-1', name: '3_Year_Audited_Financial_Statements.pdf', type: 'Audited Financials', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m5-2', name: 'CRISIL_Credit_Rating_Report.pdf', type: 'CRISIL Credit Rating', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m5-3', name: 'Certified_Liquidity_Solvency_Sheet.pdf', type: 'Solvency Sheet', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m5-4', name: 'Legal_Compliance_Non_Insolvency_Cert.pdf', type: 'Non-Insolvency Cert', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m6-1', name: 'GSTIN_PAN_Incorporation_KYC.pdf', type: 'Statutory KYC', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m6-2', name: 'ISO_14001_EHS_Certificate.pdf', type: 'ISO 14001 EHS', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m6-3', name: 'Signed_Anti_Bribery_Code_of_Conduct.pdf', type: 'Code of Conduct', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
      { id: 'doc-m6-4', name: 'ISO_27001_Information_Security.pdf', type: 'ISO 27001 Security', uploadDate: '2026-08-18', verified: true, status: 'Verified' },
    ],
    questionBreakdown: [
      { refId: 'M1-Q1', pillarId: 'M1', pillarName: 'Commercial Terms (25%)', criteria: 'Commercial Payment Terms', attachmentName: 'Terms_Net60.pdf', attachmentVerified: true, score: 5.0, weightedScore: 6.25, remarks: 'Agreed to Net 60 payment terms without price escalation penalty.' },
      { refId: 'M1-Q2', pillarId: 'M1', pillarName: 'Commercial Terms (25%)', criteria: 'Fixed Price Contract (12 Mo)', attachmentName: 'Rate_Contract_Agreement_12Mo.pdf', attachmentVerified: true, score: 5.0, weightedScore: 6.25, remarks: 'Signed 12-month fixed rate agreement attached; no commodity indexation.' },
      { refId: 'M1-Q3', pillarId: 'M1', pillarName: 'Commercial Terms (25%)', criteria: 'Inclusivity of Freight (DDP)', attachmentName: 'Freight_Policy.pdf', attachmentVerified: true, score: 4.0, weightedScore: 5.00, remarks: 'DDP terms confirmed for regional sites; remote sites capped at 2%.' },
      { refId: 'M1-Q4', pillarId: 'M1', pillarName: 'Commercial Terms (25%)', criteria: 'Volume Tier Discounting', attachmentName: 'Volume_Discount_Matrix_Tier.xlsx', attachmentVerified: true, score: 5.0, weightedScore: 6.25, remarks: 'Verified tier structure: 6.5% discount unlocked on volumes >500 units.' },

      { refId: 'M2-Q1', pillarId: 'M2', pillarName: 'Technical Capabilities (15%)', criteria: 'BOQ Spec Compliance', attachmentName: 'Technical_BOQ_Compliance_Datasheet.pdf', attachmentVerified: true, score: 5.0, weightedScore: 3.75, remarks: 'Technical datasheet verified via OCR; 100% parameter compliance.' },
      { refId: 'M2-Q2', pillarId: 'M2', pillarName: 'Technical Capabilities (15%)', criteria: 'Equipment Automation', attachmentName: 'Factory_Equipment_Automation_Log.pdf', attachmentVerified: true, score: 5.0, weightedScore: 3.75, remarks: 'Multi-axis CNC machines and robotic welding verified via audit log.' },
      { refId: 'M2-Q3', pillarId: 'M2', pillarName: 'Technical Capabilities (15%)', criteria: 'In-House R&D / Testing', attachmentName: 'NABL_Lab_Accreditation_Certificate.pdf', attachmentVerified: true, score: 5.0, weightedScore: 3.75, remarks: 'In-house NABL-accredited metallurgical testing laboratory confirmed.' },
      { refId: 'M2-Q4', pillarId: 'M2', pillarName: 'Technical Capabilities (15%)', criteria: '24/7 Technical Support', attachmentName: 'Technical_Service_SLA_Agreement.pdf', attachmentVerified: true, score: 4.0, weightedScore: 3.00, remarks: 'Dedicated field service team available in key regions; 4-hour SLA.' },

      { refId: 'M3-Q1', pillarId: 'M3', pillarName: 'Quality & Warranty (20%)', criteria: 'ISO 9001:2015 Certification', attachmentName: 'ISO_9001_TUV_Certificate.pdf', attachmentVerified: true, score: 5.0, weightedScore: 5.00, remarks: 'ISO 9001:2015 certificate valid through Nov 2028 (TÜV SÜD).' },
      { refId: 'M3-Q2', pillarId: 'M3', pillarName: 'Quality & Warranty (20%)', criteria: 'Defect Rate (PPM History)', attachmentName: 'Historical_12M_Quality_Defect_Log.pdf', attachmentVerified: true, score: 5.0, weightedScore: 5.00, remarks: 'Past 12-month quality log verified: 280 PPM recorded.' },
      { refId: 'M3-Q3', pillarId: 'M3', pillarName: 'Quality & Warranty (20%)', criteria: 'Comprehensive Warranty', attachmentName: 'Enterprise_Warranty_Policy_24Mo.pdf', attachmentVerified: true, score: 5.0, weightedScore: 5.00, remarks: 'Standard 24-month warranty provided; 36-month option available.' },
      { refId: 'M3-Q4', pillarId: 'M3', pillarName: 'Quality & Warranty (20%)', criteria: 'Batch Traceability (RFID)', attachmentName: 'RFID_Batch_Traceability_Manual.pdf', attachmentVerified: true, score: 5.0, weightedScore: 5.00, remarks: 'RFID tracking active at receiving, assembly, and dispatch stages.' },

      { refId: 'M4-Q1', pillarId: 'M4', pillarName: 'Operational Delivery (20%)', criteria: 'Verified OTIF Rate', attachmentName: '4_Quarter_OTIF_Audit_Report.pdf', attachmentVerified: true, score: 3.0, weightedScore: 3.00, remarks: 'Verified average OTIF of 92.4% over past 4 quarters (Q2 port delay).' },
      { refId: 'M4-Q2', pillarId: 'M4', pillarName: 'Operational Delivery (20%)', criteria: 'Manufacturing Lead Time', attachmentName: 'Production_SLA_Timeline_Doc.pdf', attachmentVerified: true, score: 5.0, weightedScore: 5.00, remarks: 'Standard lead time is 12 days, well within the 15-day SLA requirement.' },
      { refId: 'M4-Q3', pillarId: 'M4', pillarName: 'Operational Delivery (20%)', criteria: 'Capacity Utilization Rate', attachmentName: 'Plant_Capacity_Utilization_Audit.pdf', attachmentVerified: true, score: 5.0, weightedScore: 5.00, remarks: 'Plant operating at 74% capacity, leaving room for surge demand.' },
      { refId: 'M4-Q4', pillarId: 'M4', pillarName: 'Operational Delivery (20%)', criteria: 'Disaster Recovery (BCP)', attachmentName: 'Business_Continuity_Plan_BCP.pdf', attachmentVerified: true, score: 5.0, weightedScore: 5.00, remarks: 'BCP document attached; includes dual-sourcing & generator backup.' },

      { refId: 'M5-Q1', pillarId: 'M5', pillarName: 'Financial Stability (10%)', criteria: 'Annual Financial Turnover', attachmentName: '3_Year_Audited_Financial_Statements.pdf', attachmentVerified: true, score: 5.0, weightedScore: 2.50, remarks: 'Audited statements confirm turnover of $18.5M (≥ 5x contract value).' },
      { refId: 'M5-Q2', pillarId: 'M5', pillarName: 'Financial Stability (10%)', criteria: 'Credit Rating Score', attachmentName: 'CRISIL_Credit_Rating_Report.pdf', attachmentVerified: true, score: 5.0, weightedScore: 2.50, remarks: 'CRISIL A+ rating verified; low default risk profile.' },
      { refId: 'M5-Q3', pillarId: 'M5', pillarName: 'Financial Stability (10%)', criteria: 'Current Liquidity Ratio', attachmentName: 'Certified_Liquidity_Solvency_Sheet.pdf', attachmentVerified: true, score: 5.0, weightedScore: 2.50, remarks: 'Liquidity ratio stands at 1.82; sufficient working capital.' },
      { refId: 'M5-Q4', pillarId: 'M5', pillarName: 'Financial Stability (10%)', criteria: 'Active Litigation Claims', attachmentName: 'Legal_Compliance_Non_Insolvency_Cert.pdf', attachmentVerified: true, score: 5.0, weightedScore: 2.50, remarks: 'Legal compliance check clear; no outstanding bankruptcy or litigation.' },

      { refId: 'M6-Q1', pillarId: 'M6', pillarName: 'Governance & ESG (10%)', criteria: 'Statutory KYC & Tax Uploads', attachmentName: 'GSTIN_PAN_Incorporation_KYC.pdf', attachmentVerified: true, score: 5.0, weightedScore: 2.50, remarks: 'GSTIN, PAN, and Tax Incorporation verified against govt database.' },
      { refId: 'M6-Q2', pillarId: 'M6', pillarName: 'Governance & ESG (10%)', criteria: 'ISO 14001 / ISO 45001 Certs', attachmentName: 'ISO_14001_EHS_Certificate.pdf', attachmentVerified: true, score: 3.0, weightedScore: 1.50, remarks: 'ISO 14001 verified; ISO 45001 pending renewal in 3 months.' },
      { refId: 'M6-Q3', pillarId: 'M6', pillarName: 'Governance & ESG (10%)', criteria: 'Anti-Bribery & Ethics Policy', attachmentName: 'Signed_Anti_Bribery_Code_of_Conduct.pdf', attachmentVerified: true, score: 5.0, weightedScore: 2.50, remarks: 'Code of Conduct & Anti-Bribery agreement signed by MD.' },
      { refId: 'M6-Q4', pillarId: 'M6', pillarName: 'Governance & ESG (10%)', criteria: 'ISO 27001 / GDPR Privacy', attachmentName: 'ISO_27001_Information_Security.pdf', attachmentVerified: true, score: 5.0, weightedScore: 2.50, remarks: 'ISO 27001 certification active; enterprise security standards met.' },
    ],
  },
  {
    id: 'eval-102',
    vendorId: 'v-2',
    vendorName: 'Kiran Valve Industries',
    contactPerson: 'Amit Kumar',
    email: 'amit@kiranvalves.com',
    phone: '+91 97653 21098',
    category: 'Valves & Flow Control',
    submissionDate: '2026-08-17 11:15 UTC',
    status: 'CONDITIONAL / UNDER REVIEW',
    overallScore: 72,
    capaRequired: true,
    capaNotes: 'RFQ dispatch held. System triggered Corrective Action Plan (CAPA) for warranty extension (currently <12 months) & ISO 14001 document upload.',
    systemAction: 'RFQ DISPATCH HELD. System triggered Corrective Action Plan (CAPA) or requested document clarification.',
    moduleScores: {
      commercial: { score: 3.5, maxScore: 5, weight: 25, weightedScore: 17.5, remarks: 'Net 15 payment terms; variable price clause; 2% volume discount.' },
      technical: { score: 3.8, maxScore: 5, weight: 15, weightedScore: 11.4, remarks: '98% spec match; semi-automated lines; remote engineering support only.' },
      quality: { score: 3.4, maxScore: 5, weight: 20, weightedScore: 13.6, remarks: 'ISO 9001 active; 750 PPM defect rate; 12-month warranty; lot tracking pending.' },
      delivery: { score: 3.6, maxScore: 5, weight: 20, weightedScore: 14.4, remarks: '88% OTIF rate; 18-day lead time; capacity utilization high (92%).' },
      financial: { score: 3.2, maxScore: 5, weight: 10, weightedScore: 6.4, remarks: 'Turnover 2.1x scope; BBB rated; liquidity current ratio 1.2.' },
      governance: { score: 3.9, maxScore: 5, weight: 10, weightedScore: 7.8, remarks: 'KYC verified; ISO 14001 upload pending; ethical policy signed.' },
    },
    documents: [
      { id: 'doc-201', name: 'ISO 9001:2015 Quality Certificate.pdf', type: 'ISO Certificate', uploadDate: '2026-08-17', verified: true, status: 'Verified' },
      { id: 'doc-202', name: 'Statutory KYC & Incorporation Certificate.pdf', type: 'KYC Verification', uploadDate: '2026-08-17', verified: true, status: 'Verified' },
      { id: 'doc-203', name: 'ISO 14001 Environmental Cert.pdf', type: 'Environmental', uploadDate: '2026-08-17', verified: false, status: 'Pending Review' },
    ],
  },
  {
    id: 'eval-103',
    vendorId: 'v-3',
    vendorName: 'TechnoForce Engineering',
    contactPerson: 'Sunita Reddy',
    email: 'sunita@technoforce.in',
    phone: '+91 87654 32109',
    category: 'Electrical & Switchgear Control Panels',
    submissionDate: '2026-08-16 09:40 UTC',
    status: 'PREFERRED ENTERPRISE SUPPLIER',
    overallScore: 92,
    systemAction: 'AUTOMATIC DIRECT RFQ DISPATCH TO VENDOR INBOX. Vendor unlocked on Mode 3 roster.',
    moduleScores: {
      commercial: { score: 4.8, maxScore: 5, weight: 25, weightedScore: 24.0, remarks: 'Net 60 payment terms; 12-month fixed pricing; 8% volume tier discount.' },
      technical: { score: 4.9, maxScore: 5, weight: 15, weightedScore: 14.7, remarks: '100% spec compliance; full robotic CNC lines; accredited testing lab & 24/7 on-site team.' },
      quality: { score: 4.7, maxScore: 5, weight: 20, weightedScore: 18.8, remarks: 'ISO 9001:2015 verified; 200 PPM defect rate; 36-month warranty; full RFID lot tracking.' },
      delivery: { score: 4.5, maxScore: 5, weight: 20, weightedScore: 18.0, remarks: '98% OTIF delivery rate; 7-day lead time; 68% capacity utilization; BCP verified.' },
      financial: { score: 4.3, maxScore: 5, weight: 10, weightedScore: 8.6, remarks: 'Turnover 5.5x scope; AAA D&B credit rating; 2.1 liquidity ratio; no claims.' },
      governance: { score: 4.8, maxScore: 5, weight: 10, weightedScore: 9.6, remarks: '100% KYC verified; ISO 14001 + 45001 + 27001 GDPR certified.' },
    },
    documents: [
      { id: 'doc-301', name: 'ISO 9001:2015 Quality Certificate.pdf', type: 'ISO Certificate', uploadDate: '2026-08-16', verified: true, status: 'Verified' },
      { id: 'doc-302', name: 'In-House Testing Lab Certification.pdf', type: 'Lab Accreditation', uploadDate: '2026-08-16', verified: true, status: 'Verified' },
      { id: 'doc-303', name: 'BCP & Disaster Recovery Plan.pdf', type: 'BCP Document', uploadDate: '2026-08-16', verified: true, status: 'Verified' },
      { id: 'doc-304', name: 'D&B Credit Rating Report (AAA Rated).pdf', type: 'Credit Rating', uploadDate: '2026-08-16', verified: true, status: 'Verified' },
      { id: 'doc-305', name: 'KYC & GST Registration.pdf', type: 'KYC Verification', uploadDate: '2026-08-16', verified: true, status: 'Verified' },
      { id: 'doc-306', name: 'ISO 27001 & GDPR Compliance Audit.pdf', type: 'Data Privacy', uploadDate: '2026-08-16', verified: true, status: 'Verified' },
    ],
  },
];

export const INITIAL_BUYER_ACCOUNTS: BuyerAccount[] = [
  {
    id: 'buyer-acc-101',
    organizationName: 'Larsen & Toubro Limited',
    brandName: 'L&T Heavy Engineering & Construction',
    corporateEmail: 'client@procucev.com',
    contactPerson: 'Rajesh Sharma',
    contactDesignation: 'Chief Procurement Officer (CPO)',
    mobileNumber: '+91 98201 44820',
    gstin: '27AAACL1234F1Z5',
    panNumber: 'AAACL1234F',
    cinNumber: 'L28920MH1946PLC004768',
    industrySector: 'Heavy Engineering & Infrastructure',
    sourcingMode: 'mode_2',
    subscriptionPlan: 'version_2',
    remainingFreeRFQs: 5,
    accountSource: 'public_system',
    status: 'ACTIVE_VERIFIED',
    primaryPlantLocation: 'Navi Mumbai Logistics & Assembly Hub, MH',
    supportedMajorCategories: [
      'Engineering Spares - Mechanical',
      'Engineering Spares - Electrical',
      'Civil Works',
      'IT',
    ],
    supportedMinorCategories: [
      'Pumps & Accessories',
      'Hoses, Valves & Fittings',
      'Panels',
      'Circuit Breakers',
      'PEB Structure',
      'TMT BARS',
    ],
    totalRFQsCreated: 14,
    totalSpend: '$1.24M',
    syncTimestamp: '2026-08-28 10:30 UTC',
    createdDate: '2026-06-12',
  },
  {
    id: 'buyer-acc-102',
    organizationName: 'Tata Projects Limited',
    brandName: 'Tata Projects Industrial & EPC',
    corporateEmail: 'procurement.infra@tataprojects.com',
    contactPerson: 'Arun Varma',
    contactDesignation: 'Head of Strategic Procurement',
    mobileNumber: '+91 98110 55432',
    gstin: '27AAACT2948J1Z2',
    panNumber: 'AAACT2948J',
    cinNumber: 'U45200MH1979PLC021573',
    industrySector: 'EPC & Infrastructure Projects',
    sourcingMode: 'mode_3',
    subscriptionPlan: 'version_3',
    remainingFreeRFQs: 0,
    accountSource: 'public_system',
    status: 'SYNCED_LEGACY',
    primaryPlantLocation: 'Pune High-Tech Infrastructure Hub, MH',
    supportedMajorCategories: [
      'Civil Works',
      'Engineering Spares - Electrical',
      'CAPEX - Equipment & Machinery',
    ],
    supportedMinorCategories: [
      'TMT BARS',
      'PEB Structure',
      'Panels',
      'Air Conditioners',
      'Transformers',
    ],
    totalRFQsCreated: 28,
    totalSpend: '$3.45M',
    syncTimestamp: '2026-08-28 09:15 UTC',
    createdDate: '2026-05-18',
  },
  {
    id: 'buyer-acc-103',
    organizationName: 'JSW Infrastructure & Steel Ltd',
    brandName: 'JSW Industrial Procurement Division',
    corporateEmail: 'central.sourcing@jsw.in',
    contactPerson: 'Pooja Hegde',
    contactDesignation: 'Vice President SCM',
    mobileNumber: '+91 97654 11223',
    gstin: '29AAACJ4321K1Z8',
    panNumber: 'AAACJ4321K',
    cinNumber: 'L27102MH1994PLC152925',
    industrySector: 'Steel & Metallurgy Manufacturing',
    sourcingMode: 'mode_2',
    subscriptionPlan: 'version_2',
    remainingFreeRFQs: 3,
    accountSource: 'public_system',
    status: 'SYNCED_LEGACY',
    primaryPlantLocation: 'Vijayanagar Mega Steel Plant, KA',
    supportedMajorCategories: [
      'Engineering Spares - Mechanical',
      'Engineering Spares - Electrical',
      'Lubricants, Greases & Oils',
    ],
    supportedMinorCategories: [
      'Bearings & Accessories',
      'Pipes & Pipe Fittings',
      'Motors',
      'Cables',
    ],
    totalRFQsCreated: 19,
    totalSpend: '$2.10M',
    syncTimestamp: '2026-08-28 08:45 UTC',
    createdDate: '2026-06-01',
  },
  {
    id: 'buyer-acc-104',
    organizationName: 'Bharat Forge Limited',
    brandName: 'Kalyani Group Component Sourcing',
    corporateEmail: 'lead.buyer@bharatforge.com',
    contactPerson: 'Suresh Patil',
    contactDesignation: 'General Manager Procurement',
    mobileNumber: '+91 98223 90876',
    gstin: '27AAACB3820G1Z1',
    panNumber: 'AAACB3820G',
    cinNumber: 'L25209PN1961PLC012046',
    industrySector: 'Automotive & Precision Forging',
    sourcingMode: 'mode_1',
    subscriptionPlan: 'version_1',
    remainingFreeRFQs: 5,
    accountSource: 'public_system',
    status: 'ACTIVE_VERIFIED',
    primaryPlantLocation: 'Mundhwa Forging Works (Pune), MH',
    supportedMajorCategories: [
      'Engineering Spares - Mechanical',
      'Raw Materials',
      'Tooling',
    ],
    supportedMinorCategories: [
      'Machinery Parts',
      'Die Casting',
      'Cast Iron Parts',
      'Compressors & Accessories',
    ],
    totalRFQsCreated: 9,
    totalSpend: '$860k',
    syncTimestamp: '2026-08-28 11:20 UTC',
    createdDate: '2026-07-14',
  },
  {
    id: 'buyer-acc-105',
    organizationName: 'Godrej & Boyce Mfg. Co. Ltd.',
    brandName: 'Godrej Process Equipment Division',
    corporateEmail: 'sourcing.spares@godrej.com',
    contactPerson: 'Meera Kulkarni',
    contactDesignation: 'Senior Category Lead',
    mobileNumber: '+91 98450 67890',
    gstin: '27AAACG1829D1Z4',
    panNumber: 'AAACG1829D',
    cinNumber: 'U28993MH1932PLC001828',
    industrySector: 'Industrial Appliances & Precision Spares',
    sourcingMode: 'mode_2',
    subscriptionPlan: 'version_2',
    remainingFreeRFQs: 2,
    accountSource: 'web_registration',
    status: 'ACTIVE_VERIFIED',
    primaryPlantLocation: 'Vikhroli Industrial Complex, Mumbai, MH',
    supportedMajorCategories: [
      'Engineering Spares - Mechanical',
      'Engineering Spares - Electrical',
      'IT',
    ],
    supportedMinorCategories: [
      'Controllers',
      'Sensors',
      'Transmitters',
      'Laptop',
      'Servers',
    ],
    totalRFQsCreated: 12,
    totalSpend: '$1.05M',
    syncTimestamp: '2026-08-28 12:00 UTC',
    createdDate: '2026-07-29',
  },
  {
    id: 'buyer-acc-106',
    organizationName: 'Reliance Infrastructure Limited',
    brandName: 'R-Infra Transmission & Distribution',
    corporateEmail: 'plant.purchase@rinfra.com',
    contactPerson: 'Karan Dave',
    contactDesignation: 'Assistant VP Supply Chain',
    mobileNumber: '+91 99304 88712',
    gstin: '27AAACR4920L1Z9',
    panNumber: 'AAACR4920L',
    cinNumber: 'L75100MH1929PLC001530',
    industrySector: 'Power Distribution & Transmission',
    sourcingMode: 'mode_3',
    subscriptionPlan: 'version_3',
    remainingFreeRFQs: 0,
    accountSource: 'public_system',
    status: 'SYNCED_LEGACY',
    primaryPlantLocation: 'Dahanu Thermal & Grid Facility, MH',
    supportedMajorCategories: [
      'Engineering Spares - Electrical',
      'CAPEX - Equipment & Machinery',
    ],
    supportedMinorCategories: [
      'Panels',
      'Transformers',
      'Circuit Breakers',
      'Industrial Fans',
    ],
    totalRFQsCreated: 24,
    totalSpend: '$2.90M',
    syncTimestamp: '2026-08-28 07:30 UTC',
    createdDate: '2026-04-10',
  },
];

